CREATE SCHEMA IF NOT EXISTS dev;

CREATE TABLE IF NOT EXISTS sys_group
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    group_code      VARCHAR(64)  NOT NULL,
    group_name      VARCHAR(128) NOT NULL,
    status          VARCHAR(16)  NOT NULL DEFAULT 'ENABLED',
    remark          VARCHAR(500),
    created_at      TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_sys_group_code UNIQUE (group_code),
    CONSTRAINT ck_sys_group_status CHECK (status IN ('ENABLED', 'DISABLED'))
);

COMMENT ON TABLE sys_group IS '集团表';
COMMENT ON COLUMN sys_group.group_code IS '集团编码';
COMMENT ON COLUMN sys_group.group_name IS '集团名称';
COMMENT ON COLUMN sys_group.status IS '状态：ENABLED/DISABLED';

CREATE TABLE IF NOT EXISTS sys_store
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    group_id        BIGINT       NOT NULL,
    store_code      VARCHAR(64)  NOT NULL,
    store_name      VARCHAR(128) NOT NULL,
    status          VARCHAR(16)  NOT NULL DEFAULT 'ENABLED',
    contact_name    VARCHAR(64),
    contact_phone   VARCHAR(32),
    address         VARCHAR(255),
    remark          VARCHAR(500),
    created_at      TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_sys_store_code UNIQUE (store_code),
    CONSTRAINT fk_sys_store_group FOREIGN KEY (group_id) REFERENCES sys_group (id),
    CONSTRAINT ck_sys_store_status CHECK (status IN ('ENABLED', 'DISABLED'))
);

CREATE INDEX IF NOT EXISTS idx_sys_store_group_id ON sys_store (group_id);

COMMENT ON TABLE sys_store IS '门店表';
COMMENT ON COLUMN sys_store.group_id IS '所属集团ID';
COMMENT ON COLUMN sys_store.store_code IS '门店编码';
COMMENT ON COLUMN sys_store.store_name IS '门店名称';
COMMENT ON COLUMN sys_store.status IS '状态：ENABLED/DISABLED';
COMMENT ON COLUMN sys_store.contact_name IS '联系人';
COMMENT ON COLUMN sys_store.contact_phone IS '联系电话';
COMMENT ON COLUMN sys_store.address IS '门店地址';
COMMENT ON COLUMN sys_store.remark IS '备注';
COMMENT ON COLUMN sys_store.created_at IS '创建时间';
COMMENT ON COLUMN sys_store.updated_at IS '更新时间';

CREATE TABLE IF NOT EXISTS sys_unit
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    scope_type      VARCHAR(16)  NOT NULL DEFAULT 'PLATFORM',
    scope_id        BIGINT       NOT NULL DEFAULT 0,
    unit_code       VARCHAR(64)  NOT NULL,
    unit_name       VARCHAR(128) NOT NULL,
    unit_type       VARCHAR(16)  NOT NULL DEFAULT 'STANDARD',
    status          VARCHAR(16)  NOT NULL DEFAULT 'ENABLED',
    remark          VARCHAR(500),
    created_at      TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_sys_unit_scope_code UNIQUE (scope_type, scope_id, unit_code),
    CONSTRAINT uk_sys_unit_scope_name UNIQUE (scope_type, scope_id, unit_name),
    CONSTRAINT ck_sys_unit_scope_type CHECK (scope_type IN ('PLATFORM', 'GROUP', 'STORE')),
    CONSTRAINT ck_sys_unit_type CHECK (unit_type IN ('STANDARD', 'AUXILIARY')),
    CONSTRAINT ck_sys_unit_status CHECK (status IN ('ENABLED', 'DISABLED'))
);

COMMENT ON TABLE sys_unit IS '单位档案表';
COMMENT ON COLUMN sys_unit.scope_type IS '作用域类型：PLATFORM/GROUP/STORE';
COMMENT ON COLUMN sys_unit.scope_id IS '作用域ID，PLATFORM 固定为 0';
COMMENT ON COLUMN sys_unit.unit_code IS '单位编码';
COMMENT ON COLUMN sys_unit.unit_name IS '单位名称';
COMMENT ON COLUMN sys_unit.unit_type IS '单位类型：STANDARD/AUXILIARY';
COMMENT ON COLUMN sys_unit.status IS '状态：ENABLED/DISABLED';
COMMENT ON COLUMN sys_unit.remark IS '备注';
COMMENT ON COLUMN sys_unit.created_at IS '创建时间';
COMMENT ON COLUMN sys_unit.updated_at IS '更新时间';

ALTER TABLE sys_unit
ADD COLUMN IF NOT EXISTS scope_type VARCHAR(16) NOT NULL DEFAULT 'PLATFORM';

ALTER TABLE sys_unit
ADD COLUMN IF NOT EXISTS scope_id BIGINT NOT NULL DEFAULT 0;

ALTER TABLE sys_unit
DROP CONSTRAINT IF EXISTS uk_sys_unit_code;

ALTER TABLE sys_unit
DROP CONSTRAINT IF EXISTS uk_sys_unit_name;

INSERT INTO sys_unit (scope_type, scope_id, unit_code, unit_name, unit_type, status, remark)
VALUES ('PLATFORM', 0, 'U001', '件', 'STANDARD', 'ENABLED', '初始化数据：前端静态数据迁移')
ON CONFLICT (scope_type, scope_id, unit_code) DO NOTHING;

INSERT INTO sys_unit (scope_type, scope_id, unit_code, unit_name, unit_type, status, remark)
VALUES ('PLATFORM', 0, 'U002', '箱', 'AUXILIARY', 'ENABLED', '初始化数据：前端静态数据迁移')
ON CONFLICT (scope_type, scope_id, unit_code) DO NOTHING;

INSERT INTO sys_unit (scope_type, scope_id, unit_code, unit_name, unit_type, status, remark)
VALUES ('PLATFORM', 0, 'U003', '袋', 'AUXILIARY', 'DISABLED', '初始化数据：前端静态数据迁移')
ON CONFLICT (scope_type, scope_id, unit_code) DO NOTHING;

CREATE TABLE IF NOT EXISTS sys_user
(
    id                       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username                 VARCHAR(64)  NOT NULL,
    real_name                VARCHAR(64)  NOT NULL,
    phone                    VARCHAR(20)  NOT NULL,
    password_hash            VARCHAR(255) NOT NULL,
    password_salt            VARCHAR(128),
    status                   VARCHAR(16)  NOT NULL DEFAULT 'ENABLED',
    source_type              VARCHAR(32)  NOT NULL DEFAULT 'EXTERNAL_PUSH',
    first_login_changed_pwd  BOOLEAN      NOT NULL DEFAULT FALSE,
    last_login_at            TIMESTAMP,
    last_login_ip            VARCHAR(64),
    created_at               TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at               TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_sys_user_phone UNIQUE (phone),
    CONSTRAINT ck_sys_user_status CHECK (status IN ('ENABLED', 'DISABLED')),
    CONSTRAINT ck_sys_user_source_type CHECK (source_type IN ('EXTERNAL_PUSH', 'MANUAL', 'SYSTEM_INIT'))
);

COMMENT ON TABLE sys_user IS '统一账号表';
COMMENT ON COLUMN sys_user.username IS '登录账号，当前等于手机号';
COMMENT ON COLUMN sys_user.real_name IS '姓名';
COMMENT ON COLUMN sys_user.phone IS '手机号，全局唯一';
COMMENT ON COLUMN sys_user.password_hash IS '密码密文';
COMMENT ON COLUMN sys_user.password_salt IS '密码盐值';
COMMENT ON COLUMN sys_user.status IS '账号状态：ENABLED/DISABLED';
COMMENT ON COLUMN sys_user.source_type IS '账号来源：EXTERNAL_PUSH/MANUAL/SYSTEM_INIT';
COMMENT ON COLUMN sys_user.first_login_changed_pwd IS '首次登录是否已修改密码';
COMMENT ON COLUMN sys_user.last_login_at IS '最后登录时间';
COMMENT ON COLUMN sys_user.last_login_ip IS '最后登录IP';
COMMENT ON COLUMN sys_user.created_at IS '创建时间';
COMMENT ON COLUMN sys_user.updated_at IS '更新时间';

CREATE TABLE IF NOT EXISTS sys_user_password_log
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id           BIGINT       NOT NULL,
    operation_type    VARCHAR(32)  NOT NULL,
    operator_user_id  BIGINT,
    password_hash     VARCHAR(255) NOT NULL,
    remark            VARCHAR(500),
    created_at        TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_pwd_log_user FOREIGN KEY (user_id) REFERENCES sys_user (id),
    CONSTRAINT ck_pwd_log_operation CHECK (operation_type IN ('INIT', 'CHANGE', 'RESET'))
);

CREATE INDEX IF NOT EXISTS idx_pwd_log_user_id ON sys_user_password_log (user_id);

COMMENT ON TABLE sys_user_password_log IS '密码变更日志';
COMMENT ON COLUMN sys_user_password_log.user_id IS '用户ID';
COMMENT ON COLUMN sys_user_password_log.operation_type IS '操作类型：INIT/CHANGE/RESET';
COMMENT ON COLUMN sys_user_password_log.operator_user_id IS '操作人用户ID';
COMMENT ON COLUMN sys_user_password_log.password_hash IS '操作后密码密文';
COMMENT ON COLUMN sys_user_password_log.remark IS '备注';
COMMENT ON COLUMN sys_user_password_log.created_at IS '创建时间';

CREATE TABLE IF NOT EXISTS sys_role
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tenant_group_id   BIGINT       NOT NULL DEFAULT 0,
    role_code         VARCHAR(64)  NOT NULL,
    role_name         VARCHAR(128) NOT NULL,
    role_type         VARCHAR(16)  NOT NULL,
    data_scope_type   VARCHAR(32)  NOT NULL DEFAULT 'SELF',
    description       VARCHAR(500),
    status            VARCHAR(16)  NOT NULL DEFAULT 'ENABLED',
    created_by        BIGINT,
    created_at        TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at        TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_sys_role_tenant_code UNIQUE (tenant_group_id, role_code),
    CONSTRAINT ck_sys_role_type CHECK (role_type IN ('PLATFORM', 'GROUP', 'STORE')),
    CONSTRAINT ck_sys_role_scope CHECK (data_scope_type IN ('ALL', 'GROUP', 'STORE', 'SELF', 'CUSTOM')),
    CONSTRAINT ck_sys_role_status CHECK (status IN ('ENABLED', 'DISABLED'))
);

COMMENT ON TABLE sys_role IS '角色表';
COMMENT ON COLUMN sys_role.tenant_group_id IS '租户集团ID，0表示平台租户';
COMMENT ON COLUMN sys_role.role_type IS '角色层级：平台/集团/门店';
COMMENT ON COLUMN sys_role.role_code IS '角色编码';
COMMENT ON COLUMN sys_role.role_name IS '角色名称';
COMMENT ON COLUMN sys_role.data_scope_type IS '数据权限范围：ALL/GROUP/STORE/SELF/CUSTOM';
COMMENT ON COLUMN sys_role.description IS '角色说明';
COMMENT ON COLUMN sys_role.status IS '状态：ENABLED/DISABLED';
COMMENT ON COLUMN sys_role.created_by IS '创建人';
COMMENT ON COLUMN sys_role.created_at IS '创建时间';
COMMENT ON COLUMN sys_role.updated_at IS '更新时间';

ALTER TABLE sys_role
ADD COLUMN IF NOT EXISTS tenant_group_id BIGINT NOT NULL DEFAULT 0;

ALTER TABLE sys_role
DROP CONSTRAINT IF EXISTS uk_sys_role_code;

WITH ranked AS (
    SELECT id,
           row_number() OVER (
               PARTITION BY tenant_group_id, role_code
               ORDER BY created_at DESC NULLS LAST,
                        id DESC
           ) AS rn
    FROM sys_role
)
DELETE FROM sys_role rel
USING ranked
WHERE rel.id = ranked.id
  AND ranked.rn > 1;

ALTER TABLE sys_role
DROP CONSTRAINT IF EXISTS uk_sys_role_tenant_code;

ALTER TABLE sys_role
ADD CONSTRAINT uk_sys_role_tenant_code UNIQUE (tenant_group_id, role_code);


CREATE TABLE IF NOT EXISTS sys_menu
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    menu_code         VARCHAR(64)  NOT NULL,
    menu_name         VARCHAR(128) NOT NULL,
    parent_id         BIGINT,
    menu_type         VARCHAR(16)  NOT NULL,
    route_path        VARCHAR(255),
    component_path    VARCHAR(255),
    permission_code   VARCHAR(128),
    icon              VARCHAR(64),
    sort_no           INTEGER      NOT NULL DEFAULT 0,
    visible           BOOLEAN      NOT NULL DEFAULT TRUE,
    status            VARCHAR(16)  NOT NULL DEFAULT 'ENABLED',
    created_at        TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at        TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_sys_menu_code UNIQUE (menu_code),
    CONSTRAINT fk_sys_menu_parent FOREIGN KEY (parent_id) REFERENCES sys_menu (id),
    CONSTRAINT ck_sys_menu_type CHECK (menu_type IN ('DIRECTORY', 'MENU', 'BUTTON', 'API')),
    CONSTRAINT ck_sys_menu_status CHECK (status IN ('ENABLED', 'DISABLED'))
);

CREATE INDEX IF NOT EXISTS idx_sys_menu_parent_id ON sys_menu (parent_id);

COMMENT ON TABLE sys_menu IS '菜单/按钮/接口权限资源表';
COMMENT ON COLUMN sys_menu.menu_code IS '资源编码';
COMMENT ON COLUMN sys_menu.menu_name IS '资源名称';
COMMENT ON COLUMN sys_menu.parent_id IS '父级资源ID';
COMMENT ON COLUMN sys_menu.menu_type IS '资源类型：DIRECTORY/MENU/BUTTON/API';
COMMENT ON COLUMN sys_menu.route_path IS '前端路由地址';
COMMENT ON COLUMN sys_menu.component_path IS '前端组件路径';
COMMENT ON COLUMN sys_menu.permission_code IS '权限标识';
COMMENT ON COLUMN sys_menu.icon IS '图标';
COMMENT ON COLUMN sys_menu.sort_no IS '排序号';
COMMENT ON COLUMN sys_menu.visible IS '是否可见';
COMMENT ON COLUMN sys_menu.status IS '状态：ENABLED/DISABLED';
COMMENT ON COLUMN sys_menu.created_at IS '创建时间';
COMMENT ON COLUMN sys_menu.updated_at IS '更新时间';

CREATE TABLE IF NOT EXISTS sys_role_menu_rel
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    role_id           BIGINT       NOT NULL,
    menu_id           BIGINT       NOT NULL,
    created_at        TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_sys_role_menu UNIQUE (role_id, menu_id),
    CONSTRAINT fk_role_menu_role FOREIGN KEY (role_id) REFERENCES sys_role (id),
    CONSTRAINT fk_role_menu_menu FOREIGN KEY (menu_id) REFERENCES sys_menu (id)
);

CREATE INDEX IF NOT EXISTS idx_role_menu_role_id ON sys_role_menu_rel (role_id);
CREATE INDEX IF NOT EXISTS idx_role_menu_menu_id ON sys_role_menu_rel (menu_id);

COMMENT ON TABLE sys_role_menu_rel IS '角色-菜单权限关联表';
COMMENT ON COLUMN sys_role_menu_rel.role_id IS '角色ID';
COMMENT ON COLUMN sys_role_menu_rel.menu_id IS '菜单资源ID';
COMMENT ON COLUMN sys_role_menu_rel.created_at IS '创建时间';

CREATE TABLE IF NOT EXISTS sys_user_role_rel
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id           BIGINT       NOT NULL,
    role_id           BIGINT       NOT NULL,
    scope_type        VARCHAR(16)  NOT NULL,
    scope_id          BIGINT,
    assigned_by       BIGINT,
    assigned_at       TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    expires_at        TIMESTAMP,
    status            VARCHAR(16)  NOT NULL DEFAULT 'ENABLED',
    CONSTRAINT uk_sys_user_role_scope UNIQUE (user_id, role_id, scope_type, scope_id),
    CONSTRAINT fk_user_role_user FOREIGN KEY (user_id) REFERENCES sys_user (id),
    CONSTRAINT fk_user_role_role FOREIGN KEY (role_id) REFERENCES sys_role (id),
    CONSTRAINT ck_user_role_scope_type CHECK (scope_type IN ('PLATFORM', 'GROUP', 'STORE')),
    CONSTRAINT ck_user_role_status CHECK (status IN ('ENABLED', 'DISABLED'))
);

CREATE INDEX IF NOT EXISTS idx_user_role_user_id ON sys_user_role_rel (user_id);
CREATE INDEX IF NOT EXISTS idx_user_role_role_id ON sys_user_role_rel (role_id);
CREATE INDEX IF NOT EXISTS idx_user_role_scope ON sys_user_role_rel (scope_type, scope_id);

COMMENT ON TABLE sys_user_role_rel IS '用户角色关联表，支持平台/集团/门店范围授权';
COMMENT ON COLUMN sys_user_role_rel.user_id IS '用户ID';
COMMENT ON COLUMN sys_user_role_rel.role_id IS '角色ID';
COMMENT ON COLUMN sys_user_role_rel.scope_type IS '授权范围类型：PLATFORM/GROUP/STORE';
COMMENT ON COLUMN sys_user_role_rel.scope_id IS '授权范围对象ID';
COMMENT ON COLUMN sys_user_role_rel.assigned_by IS '授权人';
COMMENT ON COLUMN sys_user_role_rel.assigned_at IS '授权时间';
COMMENT ON COLUMN sys_user_role_rel.expires_at IS '过期时间';
COMMENT ON COLUMN sys_user_role_rel.status IS '状态：ENABLED/DISABLED';

WITH ranked AS (
    SELECT id,
           row_number() OVER (
               PARTITION BY user_id, role_id, scope_type, scope_id
               ORDER BY CASE WHEN status = 'ENABLED' THEN 0 ELSE 1 END,
                        assigned_at DESC NULLS LAST,
                        id DESC
           ) AS rn
    FROM sys_user_role_rel
)
DELETE FROM sys_user_role_rel rel
USING ranked
WHERE rel.id = ranked.id
  AND ranked.rn > 1;

WITH store_ranked AS (
    SELECT id,
           row_number() OVER (
               PARTITION BY user_id, scope_id
               ORDER BY CASE WHEN status = 'ENABLED' THEN 0 ELSE 1 END,
                        assigned_at DESC NULLS LAST,
                        id DESC
           ) AS rn
    FROM sys_user_role_rel
    WHERE scope_type = 'STORE'
)
DELETE FROM sys_user_role_rel rel
USING store_ranked
WHERE rel.id = store_ranked.id
  AND store_ranked.rn > 1;

ALTER TABLE sys_user_role_rel
DROP CONSTRAINT IF EXISTS uk_sys_user_role_scope;

ALTER TABLE sys_user_role_rel
ADD CONSTRAINT uk_sys_user_role_scope UNIQUE (user_id, role_id, scope_type, scope_id);

DROP INDEX IF EXISTS uk_sys_user_role_store_scope;

CREATE UNIQUE INDEX uk_sys_user_role_store_scope
    ON sys_user_role_rel (user_id, scope_id)
    WHERE scope_type = 'STORE';

CREATE TABLE IF NOT EXISTS sys_store_admin_rel
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    store_id          BIGINT       NOT NULL,
    user_id           BIGINT       NOT NULL,
    assigned_by       BIGINT,
    assigned_at       TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    status            VARCHAR(16)  NOT NULL DEFAULT 'ENABLED',
    CONSTRAINT uk_store_admin_store UNIQUE (store_id),
    CONSTRAINT uk_store_admin_user UNIQUE (user_id),
    CONSTRAINT fk_store_admin_store FOREIGN KEY (store_id) REFERENCES sys_store (id),
    CONSTRAINT fk_store_admin_user FOREIGN KEY (user_id) REFERENCES sys_user (id),
    CONSTRAINT ck_store_admin_status CHECK (status IN ('ENABLED', 'DISABLED'))
);

COMMENT ON TABLE sys_store_admin_rel IS '门店管理员绑定表，保证一个门店一个管理员、一个管理员一个门店';
COMMENT ON COLUMN sys_store_admin_rel.store_id IS '门店ID';
COMMENT ON COLUMN sys_store_admin_rel.user_id IS '门店管理员用户ID';
COMMENT ON COLUMN sys_store_admin_rel.assigned_by IS '分配人';
COMMENT ON COLUMN sys_store_admin_rel.assigned_at IS '分配时间';
COMMENT ON COLUMN sys_store_admin_rel.status IS '状态：ENABLED/DISABLED';

CREATE TABLE IF NOT EXISTS ext_account_import_batch
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    batch_no          VARCHAR(64)  NOT NULL,
    source_system     VARCHAR(64)  NOT NULL,
    mq_topic          VARCHAR(128),
    mq_message_key    VARCHAR(128),
    total_count       INTEGER      NOT NULL DEFAULT 0,
    success_count     INTEGER      NOT NULL DEFAULT 0,
    ignored_count     INTEGER      NOT NULL DEFAULT 0,
    failed_count      INTEGER      NOT NULL DEFAULT 0,
    process_status    VARCHAR(16)  NOT NULL DEFAULT 'PROCESSING',
    started_at        TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    finished_at       TIMESTAMP,
    created_at        TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at        TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_import_batch_no UNIQUE (batch_no),
    CONSTRAINT ck_import_batch_status CHECK (process_status IN ('PROCESSING', 'SUCCESS', 'PARTIAL_SUCCESS', 'FAILED'))
);

COMMENT ON TABLE ext_account_import_batch IS '外部账号下发批次表';
COMMENT ON COLUMN ext_account_import_batch.batch_no IS '批次号';
COMMENT ON COLUMN ext_account_import_batch.source_system IS '来源系统';
COMMENT ON COLUMN ext_account_import_batch.mq_topic IS 'MQ主题';
COMMENT ON COLUMN ext_account_import_batch.mq_message_key IS 'MQ消息键';
COMMENT ON COLUMN ext_account_import_batch.total_count IS '总记录数';
COMMENT ON COLUMN ext_account_import_batch.success_count IS '成功数';
COMMENT ON COLUMN ext_account_import_batch.ignored_count IS '忽略数';
COMMENT ON COLUMN ext_account_import_batch.failed_count IS '失败数';
COMMENT ON COLUMN ext_account_import_batch.process_status IS '处理状态：PROCESSING/SUCCESS/PARTIAL_SUCCESS/FAILED';
COMMENT ON COLUMN ext_account_import_batch.started_at IS '开始处理时间';
COMMENT ON COLUMN ext_account_import_batch.finished_at IS '处理完成时间';
COMMENT ON COLUMN ext_account_import_batch.created_at IS '创建时间';
COMMENT ON COLUMN ext_account_import_batch.updated_at IS '更新时间';

CREATE TABLE IF NOT EXISTS ext_account_import_record
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    batch_id          BIGINT       NOT NULL,
    source_system     VARCHAR(64)  NOT NULL,
    source_record_id  VARCHAR(128),
    real_name         VARCHAR(64),
    phone             VARCHAR(20),
    validate_status   VARCHAR(16)  NOT NULL DEFAULT 'PENDING',
    process_status    VARCHAR(16)  NOT NULL DEFAULT 'PENDING',
    failure_reason    VARCHAR(500),
    user_id           BIGINT,
    payload_json      TEXT,
    created_at        TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at        TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_import_record_batch FOREIGN KEY (batch_id) REFERENCES ext_account_import_batch (id),
    CONSTRAINT fk_import_record_user FOREIGN KEY (user_id) REFERENCES sys_user (id),
    CONSTRAINT ck_import_record_validate CHECK (validate_status IN ('PENDING', 'PASSED', 'REJECTED')),
    CONSTRAINT ck_import_record_process CHECK (process_status IN ('PENDING', 'SUCCESS', 'IGNORED', 'FAILED'))
);

CREATE INDEX IF NOT EXISTS idx_import_record_batch_id ON ext_account_import_record (batch_id);
CREATE INDEX IF NOT EXISTS idx_import_record_phone ON ext_account_import_record (phone);

COMMENT ON TABLE ext_account_import_record IS '外部账号下发明细表';
COMMENT ON COLUMN ext_account_import_record.batch_id IS '批次ID';
COMMENT ON COLUMN ext_account_import_record.source_system IS '来源系统';
COMMENT ON COLUMN ext_account_import_record.source_record_id IS '来源记录ID';
COMMENT ON COLUMN ext_account_import_record.real_name IS '姓名';
COMMENT ON COLUMN ext_account_import_record.phone IS '手机号';
COMMENT ON COLUMN ext_account_import_record.validate_status IS '校验状态：PENDING/PASSED/REJECTED';
COMMENT ON COLUMN ext_account_import_record.process_status IS '处理状态：PENDING/SUCCESS/IGNORED/FAILED';
COMMENT ON COLUMN ext_account_import_record.failure_reason IS '失败原因';
COMMENT ON COLUMN ext_account_import_record.user_id IS '落库后的用户ID';
COMMENT ON COLUMN ext_account_import_record.payload_json IS '原始报文';
COMMENT ON COLUMN ext_account_import_record.created_at IS '创建时间';
COMMENT ON COLUMN ext_account_import_record.updated_at IS '更新时间';

CREATE TABLE IF NOT EXISTS sys_login_log
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id           BIGINT,
    phone             VARCHAR(20),
    login_result      VARCHAR(16)  NOT NULL,
    failure_reason    VARCHAR(255),
    client_ip         VARCHAR(64),
    user_agent        VARCHAR(500),
    selected_scope    VARCHAR(16),
    selected_scope_id BIGINT,
    login_at          TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_login_log_user FOREIGN KEY (user_id) REFERENCES sys_user (id),
    CONSTRAINT ck_login_result CHECK (login_result IN ('SUCCESS', 'FAILED')),
    CONSTRAINT ck_login_scope CHECK (selected_scope IN ('PLATFORM', 'GROUP', 'STORE') OR selected_scope IS NULL)
);

CREATE INDEX IF NOT EXISTS idx_login_log_user_id ON sys_login_log (user_id);
CREATE INDEX IF NOT EXISTS idx_login_log_phone ON sys_login_log (phone);

COMMENT ON TABLE sys_login_log IS '登录日志';
COMMENT ON COLUMN sys_login_log.user_id IS '用户ID';
COMMENT ON COLUMN sys_login_log.phone IS '登录手机号';
COMMENT ON COLUMN sys_login_log.login_result IS '登录结果：SUCCESS/FAILED';
COMMENT ON COLUMN sys_login_log.failure_reason IS '失败原因';
COMMENT ON COLUMN sys_login_log.client_ip IS '客户端IP';
COMMENT ON COLUMN sys_login_log.user_agent IS '客户端标识';
COMMENT ON COLUMN sys_login_log.selected_scope IS '选定上下文类型：PLATFORM/GROUP/STORE';
COMMENT ON COLUMN sys_login_log.selected_scope_id IS '选定上下文ID';
COMMENT ON COLUMN sys_login_log.login_at IS '登录时间';

CREATE TABLE IF NOT EXISTS sys_audit_log
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    operator_user_id  BIGINT,
    operator_phone    VARCHAR(20),
    action_type       VARCHAR(64)  NOT NULL,
    target_type       VARCHAR(64)  NOT NULL,
    target_id         VARCHAR(64),
    scope_type        VARCHAR(16),
    scope_id          BIGINT,
    operation_result  VARCHAR(16)  NOT NULL DEFAULT 'SUCCESS',
    detail_json       TEXT,
    client_ip         VARCHAR(64),
    created_at        TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_audit_log_user FOREIGN KEY (operator_user_id) REFERENCES sys_user (id),
    CONSTRAINT ck_audit_log_result CHECK (operation_result IN ('SUCCESS', 'FAILED'))
);

CREATE INDEX IF NOT EXISTS idx_audit_log_user_id ON sys_audit_log (operator_user_id);
CREATE INDEX IF NOT EXISTS idx_audit_log_target ON sys_audit_log (target_type, target_id);

COMMENT ON TABLE sys_audit_log IS '审计日志';
COMMENT ON COLUMN sys_audit_log.operator_user_id IS '操作人用户ID';
COMMENT ON COLUMN sys_audit_log.operator_phone IS '操作人手机号';
COMMENT ON COLUMN sys_audit_log.action_type IS '操作类型';
COMMENT ON COLUMN sys_audit_log.target_type IS '目标对象类型';
COMMENT ON COLUMN sys_audit_log.target_id IS '目标对象ID';
COMMENT ON COLUMN sys_audit_log.scope_type IS '操作上下文类型';
COMMENT ON COLUMN sys_audit_log.scope_id IS '操作上下文ID';
COMMENT ON COLUMN sys_audit_log.operation_result IS '操作结果：SUCCESS/FAILED';
COMMENT ON COLUMN sys_audit_log.detail_json IS '变更明细JSON';
COMMENT ON COLUMN sys_audit_log.client_ip IS '客户端IP';
COMMENT ON COLUMN sys_audit_log.created_at IS '创建时间';


CREATE TABLE IF NOT EXISTS item_statistics_type
(
    id                  BIGSERIAL PRIMARY KEY,
    scope_type          VARCHAR(16)   NOT NULL DEFAULT 'PLATFORM',
    scope_id            BIGINT        NOT NULL DEFAULT 0,
    code                VARCHAR(32)   NOT NULL,
    name                VARCHAR(64)   NOT NULL,
    statistics_category VARCHAR(32)   NOT NULL,
    create_type         VARCHAR(32)   NOT NULL DEFAULT 'CUSTOM',
    created_at          TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at          TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_item_statistics_type_scope_code UNIQUE (scope_type, scope_id, code),
    CONSTRAINT uk_item_statistics_type_scope_name_category UNIQUE (scope_type, scope_id, name, statistics_category),
    CONSTRAINT ck_item_statistics_type_scope_type CHECK (scope_type IN ('PLATFORM', 'GROUP', 'STORE')),
    CONSTRAINT ck_item_statistics_type_create_type CHECK (create_type IN ('SYSTEM_BUILTIN', 'CUSTOM'))
);

ALTER TABLE item_statistics_type
ADD COLUMN IF NOT EXISTS scope_type VARCHAR(16) NOT NULL DEFAULT 'PLATFORM';

ALTER TABLE item_statistics_type
ADD COLUMN IF NOT EXISTS scope_id BIGINT NOT NULL DEFAULT 0;

ALTER TABLE item_statistics_type
DROP CONSTRAINT IF EXISTS item_statistics_type_code_key;

ALTER TABLE item_statistics_type
DROP CONSTRAINT IF EXISTS uk_item_statistics_type_code;



CREATE INDEX IF NOT EXISTS idx_item_statistics_type_scope ON item_statistics_type (scope_type, scope_id);
CREATE INDEX IF NOT EXISTS idx_item_statistics_type_name ON item_statistics_type (name);
CREATE INDEX IF NOT EXISTS idx_item_statistics_type_category ON item_statistics_type (statistics_category);

COMMENT ON TABLE item_statistics_type IS '物品统计类型';
COMMENT ON COLUMN item_statistics_type.scope_type IS '作用域类型：PLATFORM/GROUP/STORE';
COMMENT ON COLUMN item_statistics_type.scope_id IS '作用域ID，PLATFORM 固定为 0';
COMMENT ON COLUMN item_statistics_type.code IS '编码';
COMMENT ON COLUMN item_statistics_type.name IS '名称';
COMMENT ON COLUMN item_statistics_type.statistics_category IS '统计分类';
COMMENT ON COLUMN item_statistics_type.create_type IS '创建类型：SYSTEM_BUILTIN/CUSTOM';







CREATE TABLE IF NOT EXISTS item_category
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    scope_type        VARCHAR(16)  NOT NULL DEFAULT 'PLATFORM',
    scope_id          BIGINT       NOT NULL DEFAULT 0,
    category_code     VARCHAR(64)  NOT NULL,
    category_name     VARCHAR(128) NOT NULL,
    parent_category   VARCHAR(128) NOT NULL DEFAULT '物品类别',
    status            VARCHAR(16)  NOT NULL DEFAULT '启用',
    remark            VARCHAR(500),
    created_at        TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at        TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_item_category_scope_code UNIQUE (scope_type, scope_id, category_code),
    CONSTRAINT uk_item_category_scope_name UNIQUE (scope_type, scope_id, category_name),
    CONSTRAINT ck_item_category_scope_type CHECK (scope_type IN ('PLATFORM', 'GROUP', 'STORE')),
    CONSTRAINT ck_item_category_status CHECK (status IN ('启用', '停用'))
);

ALTER TABLE item_category
ADD COLUMN IF NOT EXISTS scope_type VARCHAR(16) NOT NULL DEFAULT 'PLATFORM';

ALTER TABLE item_category
ADD COLUMN IF NOT EXISTS scope_id BIGINT NOT NULL DEFAULT 0;

ALTER TABLE item_category
DROP CONSTRAINT IF EXISTS uk_item_category_code;

ALTER TABLE item_category
DROP CONSTRAINT IF EXISTS uk_item_category_name;

ALTER TABLE item_category
DROP CONSTRAINT IF EXISTS item_category_category_code_key;

ALTER TABLE item_category
DROP CONSTRAINT IF EXISTS item_category_category_name_key;



CREATE INDEX IF NOT EXISTS idx_item_category_parent ON item_category (parent_category);
CREATE INDEX IF NOT EXISTS idx_item_category_status ON item_category (status);
CREATE INDEX IF NOT EXISTS idx_item_category_scope ON item_category (scope_type, scope_id);

COMMENT ON TABLE item_category IS '物品类别表';
COMMENT ON COLUMN item_category.scope_type IS '作用域类型：PLATFORM/GROUP/STORE';
COMMENT ON COLUMN item_category.scope_id IS '作用域ID，PLATFORM 固定为 0';
COMMENT ON COLUMN item_category.category_code IS '类别编码';
COMMENT ON COLUMN item_category.category_name IS '类别名称';
COMMENT ON COLUMN item_category.parent_category IS '上级类别名称';
COMMENT ON COLUMN item_category.status IS '状态：启用/停用';
COMMENT ON COLUMN item_category.remark IS '备注';
COMMENT ON COLUMN item_category.created_at IS '创建时间';
COMMENT ON COLUMN item_category.updated_at IS '更新时间';

COMMENT ON COLUMN sys_group.id IS '主键ID';
COMMENT ON COLUMN sys_group.remark IS '备注';
COMMENT ON COLUMN sys_group.created_at IS '创建时间';
COMMENT ON COLUMN sys_group.updated_at IS '更新时间';

COMMENT ON COLUMN sys_store.id IS '主键ID';
COMMENT ON COLUMN sys_unit.id IS '主键ID';
COMMENT ON COLUMN sys_user.id IS '主键ID';
COMMENT ON COLUMN sys_user_password_log.id IS '主键ID';
COMMENT ON COLUMN sys_role.id IS '主键ID';
COMMENT ON COLUMN sys_menu.id IS '主键ID';
COMMENT ON COLUMN sys_role_menu_rel.id IS '主键ID';
COMMENT ON COLUMN sys_user_role_rel.id IS '主键ID';
COMMENT ON COLUMN sys_store_admin_rel.id IS '主键ID';
COMMENT ON COLUMN ext_account_import_batch.id IS '主键ID';
COMMENT ON COLUMN ext_account_import_record.id IS '主键ID';
COMMENT ON COLUMN sys_login_log.id IS '主键ID';
COMMENT ON COLUMN sys_audit_log.id IS '主键ID';

COMMENT ON COLUMN item_statistics_type.id IS '主键ID';
COMMENT ON COLUMN item_statistics_type.created_at IS '创建时间';
COMMENT ON COLUMN item_statistics_type.updated_at IS '更新时间';

COMMENT ON COLUMN item_category.id IS '主键ID';














CREATE TABLE IF NOT EXISTS item_tag
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    scope_type      VARCHAR(16)  NOT NULL DEFAULT 'PLATFORM',
    scope_id        BIGINT       NOT NULL DEFAULT 0,
    tag_code        VARCHAR(64)  NOT NULL,
    tag_name        VARCHAR(128) NOT NULL,
    status          VARCHAR(16)  NOT NULL DEFAULT '启用',
    remark          VARCHAR(500),
    created_at      TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_item_tag_scope_code UNIQUE (scope_type, scope_id, tag_code),
    CONSTRAINT uk_item_tag_scope_name UNIQUE (scope_type, scope_id, tag_name),
    CONSTRAINT ck_item_tag_scope_type CHECK (scope_type IN ('PLATFORM', 'GROUP', 'STORE')),
    CONSTRAINT ck_item_tag_status CHECK (status IN ('启用', '停用'))
);

CREATE INDEX IF NOT EXISTS idx_item_tag_scope ON item_tag (scope_type, scope_id);
CREATE INDEX IF NOT EXISTS idx_item_tag_status ON item_tag (status);

COMMENT ON TABLE item_tag IS '物品标签表';
COMMENT ON COLUMN item_tag.id IS '主键ID';
COMMENT ON COLUMN item_tag.scope_type IS '作用域类型：PLATFORM/GROUP/STORE';
COMMENT ON COLUMN item_tag.scope_id IS '作用域ID，PLATFORM 固定为 0';
COMMENT ON COLUMN item_tag.tag_code IS '标签编码';
COMMENT ON COLUMN item_tag.tag_name IS '标签名称';
COMMENT ON COLUMN item_tag.status IS '状态：启用/停用';
COMMENT ON COLUMN item_tag.remark IS '备注';
COMMENT ON COLUMN item_tag.created_at IS '创建时间';
COMMENT ON COLUMN item_tag.updated_at IS '更新时间';





CREATE TABLE IF NOT EXISTS item_profile
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    scope_type  VARCHAR(16)  NOT NULL DEFAULT 'PLATFORM',
    scope_id    BIGINT       NOT NULL DEFAULT 0,
    item_id     VARCHAR(64)  NOT NULL,
    item_code   VARCHAR(64)  NOT NULL,
    detail_json TEXT         NOT NULL,
    is_draft    BOOLEAN      NOT NULL DEFAULT FALSE,
    created_at  TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at  TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_item_profile_item_id UNIQUE (item_id)
);

ALTER TABLE item_profile
ADD COLUMN IF NOT EXISTS scope_type VARCHAR(16) NOT NULL DEFAULT 'PLATFORM';

ALTER TABLE item_profile
ADD COLUMN IF NOT EXISTS scope_id BIGINT NOT NULL DEFAULT 0;

ALTER TABLE item_profile
ADD COLUMN IF NOT EXISTS is_draft BOOLEAN NOT NULL DEFAULT FALSE;

CREATE INDEX IF NOT EXISTS idx_item_profile_item_code ON item_profile (item_code);
CREATE INDEX IF NOT EXISTS idx_item_profile_scope ON item_profile (scope_type, scope_id);
CREATE INDEX IF NOT EXISTS idx_item_profile_scope_draft ON item_profile (scope_type, scope_id, is_draft);

COMMENT ON TABLE item_profile IS '物品扩展详情表（JSON 持久化）';
COMMENT ON COLUMN item_profile.scope_type IS '作用域类型：PLATFORM/GROUP/STORE';
COMMENT ON COLUMN item_profile.scope_id IS '作用域ID，PLATFORM 固定为 0';
COMMENT ON COLUMN item_profile.item_id IS '物品ID（如 itm-0001）';
COMMENT ON COLUMN item_profile.item_code IS '物品编码（如 SP000001）';
COMMENT ON COLUMN item_profile.detail_json IS '完整物品表单 JSON（含营养成分表）';
COMMENT ON COLUMN item_profile.is_draft IS '是否草稿';

CREATE TABLE IF NOT EXISTS dish_category
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    scope_type        VARCHAR(16)  NOT NULL DEFAULT 'PLATFORM',
    scope_id          BIGINT       NOT NULL DEFAULT 0,
    category_code     VARCHAR(64)  NOT NULL,
    category_name     VARCHAR(128) NOT NULL,
    parent_category   VARCHAR(128) NOT NULL DEFAULT '菜品分类',
    status            VARCHAR(16)  NOT NULL DEFAULT '启用',
    created_at        TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at        TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_dish_category_scope_code UNIQUE (scope_type, scope_id, category_code),
    CONSTRAINT uk_dish_category_scope_name UNIQUE (scope_type, scope_id, category_name),
    CONSTRAINT ck_dish_category_scope_type CHECK (scope_type IN ('PLATFORM', 'GROUP', 'STORE')),
    CONSTRAINT ck_dish_category_status CHECK (status IN ('启用', '停用'))
);

ALTER TABLE dish_category
ADD COLUMN IF NOT EXISTS scope_type VARCHAR(16) NOT NULL DEFAULT 'PLATFORM';

ALTER TABLE dish_category
ADD COLUMN IF NOT EXISTS scope_id BIGINT NOT NULL DEFAULT 0;

CREATE INDEX IF NOT EXISTS idx_dish_category_scope ON dish_category (scope_type, scope_id);
CREATE INDEX IF NOT EXISTS idx_dish_category_parent ON dish_category (parent_category);
CREATE INDEX IF NOT EXISTS idx_dish_category_status ON dish_category (status);

COMMENT ON TABLE dish_category IS '菜品分类表';
COMMENT ON COLUMN dish_category.id IS '主键ID';
COMMENT ON COLUMN dish_category.scope_type IS '作用域类型：PLATFORM/GROUP/STORE';
COMMENT ON COLUMN dish_category.scope_id IS '作用域ID，PLATFORM 固定为 0';
COMMENT ON COLUMN dish_category.category_code IS '分类编码';
COMMENT ON COLUMN dish_category.category_name IS '分类名称';
COMMENT ON COLUMN dish_category.parent_category IS '上级分类名称';
COMMENT ON COLUMN dish_category.status IS '状态：启用/停用';
COMMENT ON COLUMN dish_category.created_at IS '创建时间';
COMMENT ON COLUMN dish_category.updated_at IS '更新时间';







CREATE TABLE IF NOT EXISTS dish_profile
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    scope_type        VARCHAR(16)  NOT NULL DEFAULT 'PLATFORM',
    scope_id          BIGINT       NOT NULL DEFAULT 0,
    dish_id           VARCHAR(64)  NOT NULL,
    spu_code          VARCHAR(64)  NOT NULL,
    dish_name         VARCHAR(128) NOT NULL,
    spec              VARCHAR(128),
    category_id       BIGINT       NOT NULL,
    dish_type         VARCHAR(64)  NOT NULL,
    deleted           VARCHAR(1)   NOT NULL DEFAULT 'N',
    linked_cost_card  VARCHAR(2)   NOT NULL DEFAULT '否',
    created_at        TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at        TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_dish_profile_dish_id UNIQUE (dish_id),
    CONSTRAINT ck_dish_profile_scope_type CHECK (scope_type IN ('PLATFORM', 'GROUP', 'STORE')),
    CONSTRAINT ck_dish_profile_deleted CHECK (deleted IN ('Y', 'N')),
    CONSTRAINT ck_dish_profile_linked_cost_card CHECK (linked_cost_card IN ('是', '否'))
);

ALTER TABLE dish_profile
ADD COLUMN IF NOT EXISTS scope_type VARCHAR(16) NOT NULL DEFAULT 'PLATFORM';

ALTER TABLE dish_profile
ADD COLUMN IF NOT EXISTS scope_id BIGINT NOT NULL DEFAULT 0;

CREATE INDEX IF NOT EXISTS idx_dish_profile_scope ON dish_profile (scope_type, scope_id);
CREATE INDEX IF NOT EXISTS idx_dish_profile_spu_code ON dish_profile (spu_code);
CREATE INDEX IF NOT EXISTS idx_dish_profile_category_id ON dish_profile (category_id);
CREATE INDEX IF NOT EXISTS idx_dish_profile_dish_type ON dish_profile (dish_type);
CREATE INDEX IF NOT EXISTS idx_dish_profile_deleted ON dish_profile (deleted);

COMMENT ON TABLE dish_profile IS '菜品档案表';
COMMENT ON COLUMN dish_profile.id IS '主键ID';
COMMENT ON COLUMN dish_profile.scope_type IS '作用域类型：PLATFORM/GROUP/STORE';
COMMENT ON COLUMN dish_profile.scope_id IS '作用域ID，PLATFORM 固定为 0';
COMMENT ON COLUMN dish_profile.dish_id IS '菜品ID（如 dish-0001）';
COMMENT ON COLUMN dish_profile.spu_code IS '菜品SPU编码';
COMMENT ON COLUMN dish_profile.dish_name IS '菜品名称';
COMMENT ON COLUMN dish_profile.spec IS '规格';
COMMENT ON COLUMN dish_profile.category_id IS '菜品分类ID';
COMMENT ON COLUMN dish_profile.dish_type IS '菜品类型';
COMMENT ON COLUMN dish_profile.deleted IS '是否删除：Y/N';
COMMENT ON COLUMN dish_profile.linked_cost_card IS '是否关联成本卡：是/否';
COMMENT ON COLUMN dish_profile.created_at IS '创建时间';
COMMENT ON COLUMN dish_profile.updated_at IS '更新时间';















CREATE TABLE IF NOT EXISTS supplier_profile
(
    id                                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    scope_type                         VARCHAR(16)   NOT NULL DEFAULT 'PLATFORM',
    scope_id                           BIGINT        NOT NULL DEFAULT 0,
    supplier_code                      VARCHAR(64)   NOT NULL,
    supplier_name                      VARCHAR(128)  NOT NULL,
    supplier_short_name                VARCHAR(128),
    supplier_mnemonic                  VARCHAR(64),
    supplier_category                  VARCHAR(128)  NOT NULL,
    tax_rate                           NUMERIC(8, 2) NOT NULL DEFAULT 0,
    status                             VARCHAR(16)   NOT NULL DEFAULT '启用',
    contact_person                     VARCHAR(64),
    contact_phone                      VARCHAR(32),
    email                              VARCHAR(128),
    contact_address                    VARCHAR(255),
    remark                             VARCHAR(500),
    settlement_method                  VARCHAR(32)   NOT NULL,
    order_summary_rule                 VARCHAR(32)   NOT NULL,
    input_batch_when_delivery          BOOLEAN       NOT NULL DEFAULT FALSE,
    sync_receipt_data                  BOOLEAN       NOT NULL DEFAULT TRUE,
    purchase_receipt_depend_shipping   VARCHAR(16)   NOT NULL DEFAULT '不依赖',
    delivery_depend_shipping           VARCHAR(16)   NOT NULL DEFAULT '不依赖',
    supplier_manage_inventory          BOOLEAN       NOT NULL DEFAULT FALSE,
    control_order_time                 BOOLEAN       NOT NULL DEFAULT FALSE,
    allow_close_order                  BOOLEAN       NOT NULL DEFAULT TRUE,
    reconciliation_mode                VARCHAR(255)  NOT NULL,
    scope_control                      VARCHAR(16)   NOT NULL DEFAULT '开启',
    source                             VARCHAR(16)   NOT NULL DEFAULT '集团',
    supply_relation                    VARCHAR(16)   NOT NULL DEFAULT '有',
    bind_status                        VARCHAR(16)   NOT NULL DEFAULT '未绑定',
    invoice_company_name               VARCHAR(128),
    taxpayer_id                        VARCHAR(64),
    invoice_phone                      VARCHAR(32),
    invoice_address                    VARCHAR(255),
    created_at                         TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at                         TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_supplier_profile_scope_code UNIQUE (scope_type, scope_id, supplier_code),
    CONSTRAINT ck_supplier_profile_scope_type CHECK (scope_type IN ('PLATFORM', 'GROUP', 'STORE')),
    CONSTRAINT ck_supplier_profile_status CHECK (status IN ('启用', '停用')),
    CONSTRAINT ck_supplier_profile_bind_status CHECK (bind_status IN ('已绑定', '未绑定')),
    CONSTRAINT ck_supplier_profile_source CHECK (source IN ('集团', '门店')),
    CONSTRAINT ck_supplier_profile_supply_relation CHECK (supply_relation IN ('有', '无')),
    CONSTRAINT ck_supplier_profile_scope_control CHECK (scope_control IN ('开启', '关闭'))
);

CREATE INDEX IF NOT EXISTS idx_supplier_profile_scope ON supplier_profile (scope_type, scope_id);
CREATE INDEX IF NOT EXISTS idx_supplier_profile_name ON supplier_profile (supplier_name);
CREATE INDEX IF NOT EXISTS idx_supplier_profile_category ON supplier_profile (supplier_category);
CREATE INDEX IF NOT EXISTS idx_supplier_profile_status ON supplier_profile (status);
CREATE INDEX IF NOT EXISTS idx_supplier_profile_bind_status ON supplier_profile (bind_status);
CREATE INDEX IF NOT EXISTS idx_supplier_profile_source ON supplier_profile (source);
CREATE INDEX IF NOT EXISTS idx_supplier_profile_supply_relation ON supplier_profile (supply_relation);

COMMENT ON TABLE supplier_profile IS '供应商档案主表';
COMMENT ON COLUMN supplier_profile.scope_type IS '作用域类型：PLATFORM/GROUP/STORE';
COMMENT ON COLUMN supplier_profile.scope_id IS '作用域ID，PLATFORM 固定为 0';
COMMENT ON COLUMN supplier_profile.supplier_code IS '供货商编码';
COMMENT ON COLUMN supplier_profile.supplier_name IS '供货商名称';
COMMENT ON COLUMN supplier_profile.supplier_short_name IS '供货商简称';
COMMENT ON COLUMN supplier_profile.supplier_mnemonic IS '供货商助记码';
COMMENT ON COLUMN supplier_profile.supplier_category IS '供货商类别';
COMMENT ON COLUMN supplier_profile.tax_rate IS '税率';
COMMENT ON COLUMN supplier_profile.status IS '启用状态：启用/停用';
COMMENT ON COLUMN supplier_profile.bind_status IS '绑定状态：已绑定/未绑定';
COMMENT ON COLUMN supplier_profile.source IS '来源：集团/门店';
COMMENT ON COLUMN supplier_profile.supply_relation IS '供货关系：有/无';

CREATE TABLE IF NOT EXISTS supplier_qualification
(
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    supplier_id          BIGINT       NOT NULL,
    sort_no              INTEGER      NOT NULL DEFAULT 0,
    file_name            VARCHAR(255),
    file_url             VARCHAR(500),
    qualification_type   VARCHAR(64)  NOT NULL,
    valid_to             DATE,
    status               VARCHAR(16)  NOT NULL DEFAULT '临期',
    remark               VARCHAR(500),
    created_at           TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at           TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_supplier_qualification_supplier ON supplier_qualification (supplier_id, sort_no);

COMMENT ON TABLE supplier_qualification IS '供应商资质信息';
COMMENT ON COLUMN supplier_qualification.file_name IS '资质文件名称';
COMMENT ON COLUMN supplier_qualification.file_url IS '资质文件地址';
COMMENT ON COLUMN supplier_qualification.qualification_type IS '资质类型';
COMMENT ON COLUMN supplier_qualification.valid_to IS '有效期至';
COMMENT ON COLUMN supplier_qualification.status IS '状态';

CREATE TABLE IF NOT EXISTS supplier_contract
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    supplier_id        BIGINT       NOT NULL,
    sort_no            INTEGER      NOT NULL DEFAULT 0,
    attachment_name    VARCHAR(255),
    attachment_url     VARCHAR(500),
    contract_name      VARCHAR(128),
    contract_code      VARCHAR(64),
    valid_to           DATE,
    status             VARCHAR(16),
    created_at         TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at         TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_supplier_contract_supplier ON supplier_contract (supplier_id, sort_no);

COMMENT ON TABLE supplier_contract IS '供应商合同信息';
COMMENT ON COLUMN supplier_contract.attachment_name IS '合同附件名称';
COMMENT ON COLUMN supplier_contract.attachment_url IS '合同附件地址';
COMMENT ON COLUMN supplier_contract.contract_name IS '合同名称';
COMMENT ON COLUMN supplier_contract.contract_code IS '合同编号';
COMMENT ON COLUMN supplier_contract.valid_to IS '有效期至';

CREATE TABLE IF NOT EXISTS supplier_finance_account
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    supplier_id       BIGINT       NOT NULL,
    sort_no           INTEGER      NOT NULL DEFAULT 0,
    bank_account      VARCHAR(64)  NOT NULL,
    account_name      VARCHAR(128) NOT NULL,
    bank_name         VARCHAR(128) NOT NULL,
    default_account   BOOLEAN      NOT NULL DEFAULT FALSE,
    created_at        TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at        TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_supplier_finance_account_supplier ON supplier_finance_account (supplier_id, sort_no);

COMMENT ON TABLE supplier_finance_account IS '供应商财务账户信息';
COMMENT ON COLUMN supplier_finance_account.default_account IS '是否默认银行账号';


CREATE TABLE IF NOT EXISTS supplier_category
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    scope_type        VARCHAR(16)  NOT NULL DEFAULT 'PLATFORM',
    scope_id          BIGINT       NOT NULL DEFAULT 0,
    category_code     VARCHAR(64)  NOT NULL,
    category_name     VARCHAR(128) NOT NULL,
    parent_category   VARCHAR(128) NOT NULL DEFAULT '供应商类别',
    created_at        TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at        TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_supplier_category_scope_code UNIQUE (scope_type, scope_id, category_code),
    CONSTRAINT uk_supplier_category_scope_name UNIQUE (scope_type, scope_id, category_name),
    CONSTRAINT ck_supplier_category_scope_type CHECK (scope_type IN ('PLATFORM', 'GROUP', 'STORE'))
);

CREATE INDEX IF NOT EXISTS idx_supplier_category_scope ON supplier_category (scope_type, scope_id);
CREATE INDEX IF NOT EXISTS idx_supplier_category_parent ON supplier_category (parent_category);





CREATE TABLE IF NOT EXISTS inventory_purchase_inbound
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    scope_type     VARCHAR(16)   NOT NULL DEFAULT 'PLATFORM',
    scope_id       BIGINT        NOT NULL DEFAULT 0,
    document_code  VARCHAR(64)   NOT NULL,
    inbound_date   DATE          NOT NULL,
    warehouse_name VARCHAR(128)  NOT NULL,
    supplier_name  VARCHAR(128)  NOT NULL,
    salesman_user_id BIGINT,
    salesman_name  VARCHAR(64),
    upstream_code  VARCHAR(64),
    status         VARCHAR(16)   NOT NULL DEFAULT '草稿',
    workflow_process_code VARCHAR(64),
    workflow_definition_key VARCHAR(128),
    workflow_definition_id VARCHAR(128),
    workflow_instance_id VARCHAR(64),
    workflow_task_id VARCHAR(64),
    workflow_task_name VARCHAR(128),
    workflow_status VARCHAR(16)   NOT NULL DEFAULT 'NONE',
    pending_operation VARCHAR(16) NOT NULL DEFAULT 'NONE',
    remark         VARCHAR(500),
    created_by     BIGINT,
    approved_by    BIGINT,
    approved_at    TIMESTAMP,
    created_at     TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at     TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_inventory_purchase_inbound_scope_code UNIQUE (scope_type, scope_id, document_code),
    CONSTRAINT ck_inventory_purchase_inbound_scope_type CHECK (scope_type IN ('PLATFORM', 'GROUP', 'STORE'))
);

CREATE INDEX IF NOT EXISTS idx_inventory_purchase_inbound_scope ON inventory_purchase_inbound (scope_type, scope_id);
CREATE INDEX IF NOT EXISTS idx_inventory_purchase_inbound_inbound_date ON inventory_purchase_inbound (inbound_date DESC);

ALTER TABLE inventory_purchase_inbound
    ADD COLUMN IF NOT EXISTS salesman_user_id BIGINT;

ALTER TABLE inventory_purchase_inbound
    ADD COLUMN IF NOT EXISTS salesman_name VARCHAR(64);

ALTER TABLE inventory_purchase_inbound
    ADD COLUMN IF NOT EXISTS workflow_process_code VARCHAR(64);

ALTER TABLE inventory_purchase_inbound
    ADD COLUMN IF NOT EXISTS workflow_definition_key VARCHAR(128);

ALTER TABLE inventory_purchase_inbound
    ADD COLUMN IF NOT EXISTS workflow_definition_id VARCHAR(128);

ALTER TABLE inventory_purchase_inbound
    ADD COLUMN IF NOT EXISTS workflow_instance_id VARCHAR(64);

ALTER TABLE inventory_purchase_inbound
    ADD COLUMN IF NOT EXISTS workflow_task_id VARCHAR(64);

ALTER TABLE inventory_purchase_inbound
    ADD COLUMN IF NOT EXISTS workflow_task_name VARCHAR(128);

ALTER TABLE inventory_purchase_inbound
    ADD COLUMN IF NOT EXISTS workflow_status VARCHAR(16) NOT NULL DEFAULT 'NONE';

ALTER TABLE inventory_purchase_inbound
    ADD COLUMN IF NOT EXISTS pending_operation VARCHAR(16) NOT NULL DEFAULT 'NONE';

COMMENT ON TABLE inventory_purchase_inbound IS '采购入库单';
COMMENT ON COLUMN inventory_purchase_inbound.scope_type IS '数据范围：PLATFORM/GROUP/STORE';
COMMENT ON COLUMN inventory_purchase_inbound.scope_id IS '范围ID，平台固定0';
COMMENT ON COLUMN inventory_purchase_inbound.document_code IS '单据编号';
COMMENT ON COLUMN inventory_purchase_inbound.salesman_user_id IS '业务员用户ID';
COMMENT ON COLUMN inventory_purchase_inbound.salesman_name IS '业务员名称';
COMMENT ON COLUMN inventory_purchase_inbound.workflow_process_code IS '关联流程编码';
COMMENT ON COLUMN inventory_purchase_inbound.workflow_definition_key IS '流程定义Key';
COMMENT ON COLUMN inventory_purchase_inbound.workflow_definition_id IS '流程定义ID';
COMMENT ON COLUMN inventory_purchase_inbound.workflow_instance_id IS '流程实例ID';
COMMENT ON COLUMN inventory_purchase_inbound.workflow_task_id IS '当前待办任务ID';
COMMENT ON COLUMN inventory_purchase_inbound.workflow_task_name IS '当前待办任务名称';
COMMENT ON COLUMN inventory_purchase_inbound.workflow_status IS '流程状态：NONE/RUNNING/COMPLETED/REVOKED';
COMMENT ON COLUMN inventory_purchase_inbound.pending_operation IS '待处理动作：NONE/CREATE/UPDATE/DELETE';
COMMENT ON COLUMN inventory_purchase_inbound.status IS '状态：草稿/已提交/已审核';

CREATE TABLE IF NOT EXISTS inventory_purchase_inbound_line
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    inbound_id  BIGINT         NOT NULL,
    item_code   VARCHAR(64)    NOT NULL,
    item_name   VARCHAR(128)   NOT NULL,
    quantity    NUMERIC(18,4)  NOT NULL,
    unit_price  NUMERIC(18,4)  NOT NULL DEFAULT 0,
    tax_rate    NUMERIC(10,4)  NOT NULL DEFAULT 0,
    created_at  TIMESTAMP      NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_inventory_purchase_inbound_line_inbound ON inventory_purchase_inbound_line (inbound_id);

COMMENT ON TABLE inventory_purchase_inbound_line IS '采购入库单行';

CREATE TABLE IF NOT EXISTS workflow_definition_config
(
    id                           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    scope_type                   VARCHAR(16)   NOT NULL DEFAULT 'GROUP',
    scope_id                     BIGINT        NOT NULL,
    business_code                VARCHAR(64)   NOT NULL,
    workflow_code                VARCHAR(64)   NOT NULL,
    workflow_name                VARCHAR(128)  NOT NULL,
    status                       VARCHAR(16)   NOT NULL DEFAULT 'DRAFT',
    version_no                   INTEGER       NOT NULL DEFAULT 0,
    node_config_json             TEXT          NOT NULL,
    process_definition_key       VARCHAR(128),
    process_definition_id        VARCHAR(128),
    deployed_at                  TIMESTAMP,
    created_by                   BIGINT,
    updated_by                   BIGINT,
    created_at                   TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at                   TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_workflow_definition_cfg UNIQUE (scope_type, scope_id, business_code, workflow_code),
    CONSTRAINT ck_workflow_definition_scope_type CHECK (scope_type IN ('GROUP', 'STORE')),
    CONSTRAINT ck_workflow_definition_status CHECK (status IN ('DRAFT', 'PUBLISHED'))
);

CREATE INDEX IF NOT EXISTS idx_workflow_definition_scope ON workflow_definition_config (scope_type, scope_id);

COMMENT ON TABLE workflow_definition_config IS '通用流程定义配置（集团/门店级）';
COMMENT ON COLUMN workflow_definition_config.business_code IS '业务编码，如PURCHASE_INBOUND/ORDER_RECONCILE';
COMMENT ON COLUMN workflow_definition_config.node_config_json IS '流程节点配置JSON';
COMMENT ON COLUMN workflow_definition_config.status IS '状态：DRAFT/PUBLISHED';

CREATE TABLE IF NOT EXISTS workflow_process_registry
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    scope_type     VARCHAR(16)   NOT NULL DEFAULT 'GROUP',
    scope_id       BIGINT        NOT NULL,
    process_code   VARCHAR(64)   NOT NULL,
    business_name  VARCHAR(128)  NOT NULL,
    template_id    VARCHAR(64),
    created_by     BIGINT,
    updated_by     BIGINT,
    created_at     TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at     TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_workflow_process_registry UNIQUE (scope_type, scope_id, process_code),
    CONSTRAINT ck_workflow_process_scope_type CHECK (scope_type IN ('GROUP'))
);

CREATE INDEX IF NOT EXISTS idx_workflow_process_scope ON workflow_process_registry (scope_type, scope_id);

COMMENT ON TABLE workflow_process_registry IS '流程管理主表（集团级）';
COMMENT ON COLUMN workflow_process_registry.process_code IS '流程ID';
COMMENT ON COLUMN workflow_process_registry.template_id IS '绑定模板ID';

CREATE TABLE IF NOT EXISTS workflow_process_store_binding
(
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    process_registry_id  BIGINT      NOT NULL,
    group_id             BIGINT      NOT NULL,
    store_id             BIGINT      NOT NULL,
    created_by           BIGINT,
    updated_by           BIGINT,
    created_at           TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at           TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_workflow_process_store_binding UNIQUE (process_registry_id, store_id),
    CONSTRAINT fk_workflow_process_binding_process FOREIGN KEY (process_registry_id) REFERENCES workflow_process_registry (id),
    CONSTRAINT fk_workflow_process_binding_group FOREIGN KEY (group_id) REFERENCES sys_group (id),
    CONSTRAINT fk_workflow_process_binding_store FOREIGN KEY (store_id) REFERENCES sys_store (id)
);

CREATE INDEX IF NOT EXISTS idx_workflow_process_store_binding_group ON workflow_process_store_binding (group_id, process_registry_id);
CREATE INDEX IF NOT EXISTS idx_workflow_process_store_binding_store ON workflow_process_store_binding (store_id);

COMMENT ON TABLE workflow_process_store_binding IS '流程与门店绑定关系表（集团级）';
COMMENT ON COLUMN workflow_process_store_binding.process_registry_id IS '流程管理主表ID';
COMMENT ON COLUMN workflow_process_store_binding.group_id IS '集团ID';
COMMENT ON COLUMN workflow_process_store_binding.store_id IS '门店ID';

CREATE TABLE IF NOT EXISTS inventory_balance
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    scope_type     VARCHAR(16)   NOT NULL DEFAULT 'PLATFORM',
    scope_id       BIGINT        NOT NULL DEFAULT 0,
    warehouse_name VARCHAR(128)  NOT NULL,
    item_code      VARCHAR(64)   NOT NULL,
    item_name      VARCHAR(128)  NOT NULL,
    quantity       NUMERIC(18,4) NOT NULL DEFAULT 0,
    created_at     TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at     TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_inventory_balance_scope_wh_item UNIQUE (scope_type, scope_id, warehouse_name, item_code),
    CONSTRAINT ck_inventory_balance_scope_type CHECK (scope_type IN ('PLATFORM', 'GROUP', 'STORE'))
);

CREATE INDEX IF NOT EXISTS idx_inventory_balance_scope ON inventory_balance (scope_type, scope_id, warehouse_name);

COMMENT ON TABLE inventory_balance IS '库存结存';

CREATE TABLE IF NOT EXISTS inventory_transaction
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    scope_type     VARCHAR(16)   NOT NULL DEFAULT 'PLATFORM',
    scope_id       BIGINT        NOT NULL DEFAULT 0,
    biz_type       VARCHAR(64)   NOT NULL,
    biz_id         BIGINT        NOT NULL,
    biz_line_id    BIGINT,
    warehouse_name VARCHAR(128)  NOT NULL,
    item_code      VARCHAR(64)   NOT NULL,
    item_name      VARCHAR(128)  NOT NULL,
    quantity_delta NUMERIC(18,4) NOT NULL,
    before_qty     NUMERIC(18,4) NOT NULL,
    after_qty      NUMERIC(18,4) NOT NULL,
    operator_id    BIGINT,
    created_at     TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_inventory_transaction_scope_type CHECK (scope_type IN ('PLATFORM', 'GROUP', 'STORE'))
);

CREATE INDEX IF NOT EXISTS idx_inventory_transaction_scope ON inventory_transaction (scope_type, scope_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_inventory_transaction_biz ON inventory_transaction (biz_type, biz_id);

COMMENT ON TABLE inventory_transaction IS '库存流水';

CREATE TABLE IF NOT EXISTS sys_warehouse
(
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    store_id              BIGINT       NOT NULL,
    group_id              BIGINT       NOT NULL,
    warehouse_code        VARCHAR(64)  NOT NULL,
    warehouse_name        VARCHAR(128) NOT NULL,
    department            VARCHAR(64),
    status                VARCHAR(16)  NOT NULL DEFAULT 'ENABLED',
    warehouse_type        VARCHAR(32)  NOT NULL DEFAULT '普通仓库',
    contact_name          VARCHAR(64),
    contact_phone         VARCHAR(32),
    region_path           VARCHAR(255),
    address               VARCHAR(500),
    target_gross_margin   VARCHAR(16),
    ideal_purchase_sale_ratio VARCHAR(32),
    is_default            BOOLEAN      NOT NULL DEFAULT FALSE,
    remark                VARCHAR(500),
    created_at            TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at            TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_warehouse_code UNIQUE (warehouse_code),
    CONSTRAINT fk_warehouse_store FOREIGN KEY (store_id) REFERENCES sys_store (id),
    CONSTRAINT fk_warehouse_group FOREIGN KEY (group_id) REFERENCES sys_group (id),
    CONSTRAINT ck_warehouse_status CHECK (status IN ('ENABLED', 'DISABLED')),
    CONSTRAINT ck_warehouse_type CHECK (warehouse_type IN ('出品及生产部门', '行政部门', '普通仓库'))
);

ALTER TABLE sys_warehouse
ADD COLUMN IF NOT EXISTS store_id BIGINT;

UPDATE sys_warehouse warehouse
SET store_id = (
    SELECT store.id
    FROM sys_store store
    WHERE store.group_id = warehouse.group_id
    ORDER BY store.id
    LIMIT 1
)
WHERE warehouse.store_id IS NULL;

ALTER TABLE sys_warehouse
DROP CONSTRAINT IF EXISTS fk_warehouse_store;

ALTER TABLE sys_warehouse
ADD CONSTRAINT fk_warehouse_store FOREIGN KEY (store_id) REFERENCES sys_store (id);

CREATE INDEX IF NOT EXISTS idx_warehouse_group_id ON sys_warehouse (group_id);
CREATE INDEX IF NOT EXISTS idx_warehouse_store_id ON sys_warehouse (store_id);
CREATE INDEX IF NOT EXISTS idx_warehouse_status ON sys_warehouse (status);

COMMENT ON TABLE sys_warehouse IS '仓库档案表';
COMMENT ON COLUMN sys_warehouse.store_id IS '所属门店ID';
COMMENT ON COLUMN sys_warehouse.group_id IS '所属集团ID';
COMMENT ON COLUMN sys_warehouse.warehouse_code IS '仓库编码';
COMMENT ON COLUMN sys_warehouse.warehouse_name IS '仓库名称';
COMMENT ON COLUMN sys_warehouse.department IS '所属部门';
COMMENT ON COLUMN sys_warehouse.status IS '状态：ENABLED/DISABLED';
COMMENT ON COLUMN sys_warehouse.warehouse_type IS '仓库类型：出品及生产部门/行政部门/普通仓库';
COMMENT ON COLUMN sys_warehouse.contact_name IS '联系人';
COMMENT ON COLUMN sys_warehouse.contact_phone IS '联系电话';
COMMENT ON COLUMN sys_warehouse.region_path IS '区域路径（省/市/区）';
COMMENT ON COLUMN sys_warehouse.address IS '详细地址';
COMMENT ON COLUMN sys_warehouse.target_gross_margin IS '目标毛利率';
COMMENT ON COLUMN sys_warehouse.ideal_purchase_sale_ratio IS '理想采销比';
COMMENT ON COLUMN sys_warehouse.is_default IS '是否默认仓库';
COMMENT ON COLUMN sys_warehouse.remark IS '备注';

-- ============================================================
-- 仓库物品规则表（主表）
-- ============================================================
CREATE TABLE IF NOT EXISTS warehouse_item_rule
(
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    group_id                BIGINT       NOT NULL,
    rule_code               VARCHAR(64)  NOT NULL,
    rule_name               VARCHAR(128) NOT NULL,
    business_control        BOOLEAN      NOT NULL DEFAULT FALSE,
    control_order           BOOLEAN      NOT NULL DEFAULT FALSE,
    control_purchase_inbound BOOLEAN     NOT NULL DEFAULT FALSE,
    control_transfer_inbound BOOLEAN     NOT NULL DEFAULT FALSE,
    status                  VARCHAR(16)  NOT NULL DEFAULT 'ENABLED',
    created_by              VARCHAR(64),
    created_at              TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_by              VARCHAR(64),
    updated_at              TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_rule_code UNIQUE (rule_code),
    CONSTRAINT fk_rule_group FOREIGN KEY (group_id) REFERENCES sys_group (id)
);

CREATE INDEX IF NOT EXISTS idx_rule_group_id ON warehouse_item_rule (group_id);
CREATE INDEX IF NOT EXISTS idx_rule_status ON warehouse_item_rule (status);

COMMENT ON TABLE warehouse_item_rule IS '仓库物品规则主表';
COMMENT ON COLUMN warehouse_item_rule.group_id IS '所属集团ID';
COMMENT ON COLUMN warehouse_item_rule.rule_code IS '规则编码';
COMMENT ON COLUMN warehouse_item_rule.rule_name IS '规则名称';
COMMENT ON COLUMN warehouse_item_rule.business_control IS '是否启用业务管控';
COMMENT ON COLUMN warehouse_item_rule.control_order IS '管控适用机构订货';
COMMENT ON COLUMN warehouse_item_rule.control_purchase_inbound IS '管控适用机构采购入库';
COMMENT ON COLUMN warehouse_item_rule.control_transfer_inbound IS '管控适用机构调拨入库';
COMMENT ON COLUMN warehouse_item_rule.status IS '状态：ENABLED/DISABLED';
COMMENT ON COLUMN warehouse_item_rule.created_by IS '创建人';
COMMENT ON COLUMN warehouse_item_rule.created_at IS '创建时间';
COMMENT ON COLUMN warehouse_item_rule.updated_by IS '最后修改人';
COMMENT ON COLUMN warehouse_item_rule.updated_at IS '最后修改时间';

-- ============================================================
-- 规则适用物品明细表
-- ============================================================
CREATE TABLE IF NOT EXISTS warehouse_item_rule_item
(
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    rule_id                 BIGINT       NOT NULL,
    item_code               VARCHAR(64),
    item_name               VARCHAR(128),
    spec_model              VARCHAR(128),
    item_category           VARCHAR(64),
    sort_order              INT          DEFAULT 0,
    created_at              TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_rti_rule FOREIGN KEY (rule_id) REFERENCES warehouse_item_rule (id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_rti_rule_id ON warehouse_item_rule_item (rule_id);

COMMENT ON TABLE warehouse_item_rule_item IS '规则适用物品明细';
COMMENT ON COLUMN warehouse_item_rule_item.rule_id IS '规则ID';
COMMENT ON COLUMN warehouse_item_rule_item.item_code IS '物品编码';
COMMENT ON COLUMN warehouse_item_rule_item.item_name IS '物品名称';
COMMENT ON COLUMN warehouse_item_rule_item.spec_model IS '规格型号';
COMMENT ON COLUMN warehouse_item_rule_item.item_category IS '物品类别';
COMMENT ON COLUMN warehouse_item_rule_item.sort_order IS '排序';

-- ============================================================
-- 规则适用分类明细表
-- ============================================================
CREATE TABLE IF NOT EXISTS warehouse_item_rule_category
(
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    rule_id                 BIGINT       NOT NULL,
    category_code           VARCHAR(64),
    category_name           VARCHAR(128),
    parent_category         VARCHAR(128),
    child_category          VARCHAR(128),
    sort_order              INT          DEFAULT 0,
    created_at              TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_rtc_rule FOREIGN KEY (rule_id) REFERENCES warehouse_item_rule (id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_rtc_rule_id ON warehouse_item_rule_category (rule_id);

COMMENT ON TABLE warehouse_item_rule_category IS '规则适用分类明细';
COMMENT ON COLUMN warehouse_item_rule_category.rule_id IS '规则ID';
COMMENT ON COLUMN warehouse_item_rule_category.category_code IS '分类编码';
COMMENT ON COLUMN warehouse_item_rule_category.category_name IS '分类名称';
COMMENT ON COLUMN warehouse_item_rule_category.parent_category IS '上级分类';
COMMENT ON COLUMN warehouse_item_rule_category.child_category IS '下级分类';
COMMENT ON COLUMN warehouse_item_rule_category.sort_order IS '排序';

-- ============================================================
-- 规则适用仓库明细表
-- ============================================================
CREATE TABLE IF NOT EXISTS warehouse_item_rule_warehouse
(
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    rule_id                 BIGINT       NOT NULL,
    warehouse_id            BIGINT,
    warehouse_name          VARCHAR(128),
    sort_order              INT          DEFAULT 0,
    created_at              TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_rtw_rule FOREIGN KEY (rule_id) REFERENCES warehouse_item_rule (id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_rtw_rule_id ON warehouse_item_rule_warehouse (rule_id);
COMMENT ON TABLE warehouse_item_rule_warehouse IS '规则适用仓库明细';
COMMENT ON COLUMN warehouse_item_rule_warehouse.rule_id IS '规则ID';
COMMENT ON COLUMN warehouse_item_rule_warehouse.warehouse_id IS '仓库/档口ID';
COMMENT ON COLUMN warehouse_item_rule_warehouse.warehouse_name IS '仓库/档口名称';
COMMENT ON COLUMN warehouse_item_rule_warehouse.sort_order IS '排序';

