import type { RouteRecordRaw } from 'vue-router';

type LazyView = NonNullable<RouteRecordRaw['component']>;

const featureFallback = () => import('@/views/feature/index.vue');

const menuViewRegistry: Record<string, LazyView> = {
  'system.group-management.index': () => import('@/views/system/group-management.vue'),
  'system.store-management.index': () => import('@/views/system/store-management.vue'),
  'system.user-management.index': () => import('@/views/system/user-management.vue'),
  'system.role-management.index': () => import('@/views/system/role-management.vue'),
  'system.menu-permission-management.index': () => import('@/views/system/menu-permission-management.vue'),
  'system.menu-maintenance.index': () => import('@/views/system/menu-maintenance.vue'),
  'system.dictionary-management.index': () => import('@/views/system/dictionary-management.vue'),
  'system.unit-management.index': () => import('@/views/system/unit-management.vue'),
  'system.org-management.index': () => import('@/views/system/org-management.vue'),
  'system.warehouse-management.index': () => import('@/views/system/warehouse-management.vue'),
  'system.warehouse-item-rule-management.index': () => import('@/views/system/warehouse-item-rule-management.vue'),
  'system.workflow-publish-history-management.index': () => import('@/views/system/workflow-publish-history-management.vue'),
  'order.order-document.index': () => import('@/views/order/order-document.vue'),
  'order.receipt-document.index': () => import('@/views/order/receipt-document.vue'),
  'order.difference-document.index': () => import('@/views/order/difference-document.vue'),
  'order.return-document.index': () => import('@/views/order/return-document.vue'),
  'order.third-party-transfer-document.index': () => import('@/views/order/third-party-transfer-document.vue'),
  'purchase.purchase-pricing.index': () => import('@/views/purchase/purchase-pricing.vue'),
  'purchase.pricing-adjustment-management.index': () => import('@/views/purchase/pricing-adjustment-management.vue'),
  'purchase.purchase-pricing-detail.index': () => import('@/views/purchase/purchase-pricing-detail.vue'),
  'purchase.purchase-application.index': () => import('@/views/purchase/purchase-application.vue'),
  'purchase.purchase-application-review.index': () => import('@/views/purchase/purchase-application-review.vue'),
  'purchase.purchase-order.index': () => import('@/views/purchase/purchase-order.vue'),
  'purchase.purchase-receipt.index': () => import('@/views/purchase/purchase-receipt.vue'),
  'purchase.purchase-return.index': () => import('@/views/purchase/purchase-return.vue'),
  'inventory.warehouse-opening-balance.index': () => import('@/views/inventory/warehouse-opening-balance.vue'),
  'inventory.purchase-inbound.index': () => import('@/views/inventory/purchase-inbound.vue'),
  'inventory.purchase-return-outbound.index': () => import('@/views/inventory/purchase-return-outbound.vue'),
  'inventory.department-picking.index': () => import('@/views/inventory/department-picking.vue'),
  'inventory.department-return.index': () => import('@/views/inventory/department-return.vue'),
  'inventory.stock-transfer.index': () => import('@/views/inventory/stock-transfer.vue'),
  'inventory.stock-transfer-inbound.index': () => import('@/views/inventory/stock-transfer-inbound.vue'),
  'inventory.department-transfer.index': () => import('@/views/inventory/department-transfer.vue'),
  'inventory.store-transfer.index': () => import('@/views/inventory/store-transfer.vue'),
  'inventory.damage-outbound.index': () => import('@/views/inventory/damage-outbound.vue'),
  'inventory.other-inbound.index': () => import('@/views/inventory/other-inbound.vue'),
  'inventory.other-outbound.index': () => import('@/views/inventory/other-outbound.vue'),
  'inventory.production-inbound.index': () => import('@/views/inventory/production-inbound.vue'),
  'inventory.customer-sales-outbound.index': () => import('@/views/inventory/customer-sales-outbound.vue'),
  'inventory.customer-return-inbound.index': () => import('@/views/inventory/customer-return-inbound.vue'),
  'inventory.stock-transfer-outbound.index': () => import('@/views/inventory/stock-transfer-outbound.vue'),
  'inventory.inventory-check.index': () => import('@/views/inventory/inventory-check.vue'),
  'inventory.multi-inventory-check.index': () => import('@/views/inventory/multi-inventory-check.vue'),
  'inventory.profit-inbound.index': () => import('@/views/inventory/profit-inbound.vue'),
  'inventory.loss-outbound.index': () => import('@/views/inventory/loss-outbound.vue'),
  'inventory.dish-consumption-outbound.index': () => import('@/views/inventory/dish-consumption-outbound.vue'),
  'inventory.batch-adjustment.index': () => import('@/views/inventory/batch-adjustment.vue'),
  'inventory.inventory-template.index': () => import('@/views/inventory/inventory-template.vue'),
  'inventory.transfer-group.index': () => import('@/views/inventory/transfer-group.vue'),
  'inventory.stock-limits.index': () => import('@/views/inventory/stock-limits.vue'),
  'inventory.stock-lock.index': () => import('@/views/inventory/stock-lock.vue'),
  'inventory.stock-lock-log.index': () => import('@/views/inventory/stock-lock-log.vue'),
  'report.purchase-order-status-tracking.index': () => import('@/views/report/purchase-order-status-tracking-report.vue'),
  'report.purchase-return-status-tracking.index': () => import('@/views/report/purchase-return-status-tracking-report.vue'),
  'report.purchase-item-price-analysis.index': () => import('@/views/report/purchase-item-price-analysis-report.vue'),
  'report.realtime-stock-query.index': () => import('@/views/inventory/realtime-stock-query.vue'),
  'report.dish-consumption-outbound-report.index': () => import('@/views/inventory/dish-consumption-outbound-report.vue'),
  'report.inventory-profit-loss.index': () => import('@/views/report/inventory-profit-loss-report.vue'),
  'report.inventory-inout-detail-report.index': () => import('@/views/inventory/inventory-inout-detail-report.vue'),
  'report.inventory-inout-summary.index': () => import('@/views/report/inventory-inout-summary-report.vue'),
  'report.stock-inout-summary.index': () => import('@/views/report/stock-inout-summary-report.vue'),
  'report.other-inout-summary.index': () => import('@/views/report/other-inout-summary-report.vue'),
  'report.inter-org-transfer-detail.index': () => import('@/views/report/inter-org-transfer-detail-report.vue'),
  'report.inter-org-transfer-summary.index': () => import('@/views/report/inter-org-transfer-summary-report.vue'),
  'report.item-batch-trace.index': () => import('@/views/report/item-batch-trace-report.vue'),
  'report.stagnant-stock.index': () => import('@/views/report/stagnant-stock-report.vue'),
  'report.stock-turnover-rate.index': () => import('@/views/report/stock-turnover-rate-report.vue'),
  'report.stock-warning.index': () => import('@/views/report/stock-warning-report.vue'),
  'items.management.index': () => import('@/views/items/management.vue'),
  'items.category-management.index': () => import('@/views/items/category-management.vue'),
  'items.statistics-type-management.index': () => import('@/views/items/statistics-type-management.vue'),
  'items.tag-management.index': () => import('@/views/items/tag-management.vue'),
  'supplier.management.index': () => import('@/views/supplier/management.vue'),
  'cost.cost-card-archive.index': () => import('@/views/cost/cost-card-archive.vue'),
  'cost.cost-card-setting.index': () => import('@/views/cost/cost-card-setting.vue'),
  'cost.dish-warehouse-link.index': () => import('@/views/cost/dish-warehouse-link.vue'),
  'cost.expense-warehouse-link.index': () => import('@/views/cost/expense-warehouse-link.vue'),
};

export const resolveMenuView = (componentKey?: string | null): LazyView => {
  if (!componentKey) {
    return featureFallback;
  }
  return menuViewRegistry[componentKey] ?? featureFallback;
};
