import type { RouteRecordRaw } from 'vue-router';

export const inventoryRoutes: RouteRecordRaw[] = [
  {
          path: 'inventory/period-openings/create',
          name: 'PeriodOpeningCreate',
          component: () => import('@/views/inventory/period-opening-create.vue'),
          meta: {
            title: '新增期初库存',
            activeMenu: '/inventory/period-openings',
            breadcrumbs: ['库存管理', '库存单据', '期初库存', '新增期初库存'],
            openKeys: ['m4', 'm4-m1'],
          },
        },
  {
          path: 'inventory/period-openings/view/:id',
          name: 'PeriodOpeningView',
          component: () => import('@/views/inventory/period-opening-create.vue'),
          meta: {
            title: '查看期初库存',
            activeMenu: '/inventory/period-openings',
            breadcrumbs: ['库存管理', '库存单据', '期初库存', '查看期初库存'],
            openKeys: ['m4', 'm4-m1'],
          },
        },
  {
          path: 'inventory/period-openings/edit/:id',
          name: 'PeriodOpeningEdit',
          component: () => import('@/views/inventory/period-opening-create.vue'),
          meta: {
            title: '编辑期初库存',
            activeMenu: '/inventory/period-openings',
            breadcrumbs: ['库存管理', '库存单据', '期初库存', '编辑期初库存'],
            openKeys: ['m4', 'm4-m1'],
          },
        },
  {
          path: 'inventory/purchase-inbounds/create',
          name: 'PurchaseInboundCreate',
          component: () => import('@/views/inventory/purchase-inbound-create.vue'),
          meta: {
            title: '新增采购入库',
            activeMenu: '/inventory/purchase-inbounds',
            breadcrumbs: ['库存管理', '库存单据', '采购入库', '新增采购入库'],
            openKeys: ['m4', 'm4-m1'],
          },
        },
  {
          path: 'inventory/purchase-inbounds/view/:id',
          name: 'PurchaseInboundView',
          component: () => import('@/views/inventory/purchase-inbound-create.vue'),
          meta: {
            title: '查看采购入库',
            activeMenu: '/inventory/purchase-inbounds',
            breadcrumbs: ['库存管理', '库存单据', '采购入库', '查看采购入库'],
            openKeys: ['m4', 'm4-m1'],
          },
        },
  {
          path: 'inventory/purchase-inbounds/edit/:id',
          name: 'PurchaseInboundEdit',
          component: () => import('@/views/inventory/purchase-inbound-create.vue'),
          meta: {
            title: '编辑采购入库',
            activeMenu: '/inventory/purchase-inbounds',
            breadcrumbs: ['库存管理', '库存单据', '采购入库', '编辑采购入库'],
            openKeys: ['m4', 'm4-m1'],
          },
        },
  {
          path: 'inventory/purchase-return-outbounds/create',
          name: 'PurchaseReturnOutboundCreate',
          component: () => import('@/views/inventory/purchase-return-outbound-create.vue'),
          meta: {
            title: '新增采购退货出库',
            activeMenu: '/inventory/purchase-return-outbounds',
            breadcrumbs: ['库存管理', '库存单据', '采购退货出库', '新增采购退货出库'],
            openKeys: ['m4', 'm4-m1'],
          },
        },
  {
          path: 'inventory/purchase-return-outbounds/view/:id',
          name: 'PurchaseReturnOutboundView',
          component: () => import('@/views/inventory/purchase-return-outbound-create.vue'),
          meta: {
            title: '查看采购退货出库',
            activeMenu: '/inventory/purchase-return-outbounds',
            breadcrumbs: ['库存管理', '库存单据', '采购退货出库', '查看采购退货出库'],
            openKeys: ['m4', 'm4-m1'],
          },
        },
  {
          path: 'inventory/purchase-return-outbounds/edit/:id',
          name: 'PurchaseReturnOutboundEdit',
          component: () => import('@/views/inventory/purchase-return-outbound-create.vue'),
          meta: {
            title: '编辑采购退货出库',
            activeMenu: '/inventory/purchase-return-outbounds',
            breadcrumbs: ['库存管理', '库存单据', '采购退货出库', '编辑采购退货出库'],
            openKeys: ['m4', 'm4-m1'],
          },
        },
  {
          path: 'inventory/department-pickings/create',
          name: 'DepartmentPickingCreate',
          component: () => import('@/views/inventory/department-picking-create.vue'),
          meta: {
            title: '新增部门领料',
            activeMenu: '/inventory/department-pickings',
            breadcrumbs: ['库存管理', '库存单据', '部门领料', '新增部门领料'],
            openKeys: ['m4', 'm4-m1'],
          },
        },
  {
          path: 'inventory/department-pickings/view/:id',
          name: 'DepartmentPickingView',
          component: () => import('@/views/inventory/department-picking-create.vue'),
          meta: {
            title: '查看部门领料',
            activeMenu: '/inventory/department-pickings',
            breadcrumbs: ['库存管理', '库存单据', '部门领料', '查看部门领料'],
            openKeys: ['m4', 'm4-m1'],
          },
        },
  {
          path: 'inventory/department-pickings/edit/:id',
          name: 'DepartmentPickingEdit',
          component: () => import('@/views/inventory/department-picking-create.vue'),
          meta: {
            title: '编辑部门领料',
            activeMenu: '/inventory/department-pickings',
            breadcrumbs: ['库存管理', '库存单据', '部门领料', '编辑部门领料'],
            openKeys: ['m4', 'm4-m1'],
          },
        },
  {
          path: 'inventory/department-returns/create',
          name: 'DepartmentReturnCreate',
          component: () => import('@/views/inventory/department-return-create.vue'),
          meta: {
            title: '新增部门退料',
            activeMenu: '/inventory/department-returns',
            breadcrumbs: ['库存管理', '库存单据', '部门退料', '新增部门退料'],
            openKeys: ['m4', 'm4-m1'],
          },
        },
  {
          path: 'inventory/department-returns/view/:id',
          name: 'DepartmentReturnView',
          component: () => import('@/views/inventory/department-return-create.vue'),
          meta: {
            title: '查看部门退料',
            activeMenu: '/inventory/department-returns',
            breadcrumbs: ['库存管理', '库存单据', '部门退料', '查看部门退料'],
            openKeys: ['m4', 'm4-m1'],
          },
        },
  {
          path: 'inventory/department-returns/edit/:id',
          name: 'DepartmentReturnEdit',
          component: () => import('@/views/inventory/department-return-create.vue'),
          meta: {
            title: '编辑部门退料',
            activeMenu: '/inventory/department-returns',
            breadcrumbs: ['库存管理', '库存单据', '部门退料', '编辑部门退料'],
            openKeys: ['m4', 'm4-m1'],
          },
        },
  {
          path: 'inventory/stock-transfers/create',
          name: 'StockTransferCreate',
          component: () => import('@/views/inventory/stock-transfer-create.vue'),
          meta: {
            title: '新增移库单',
            activeMenu: '/inventory/stock-transfers',
            breadcrumbs: ['库存管理', '库存单据', '移库单', '新增移库单'],
            openKeys: ['m4', 'm4-m1'],
          },
        },
  {
          path: 'inventory/stock-transfers/view/:id',
          name: 'StockTransferView',
          component: () => import('@/views/inventory/stock-transfer-create.vue'),
          meta: {
            title: '查看移库单',
            activeMenu: '/inventory/stock-transfers',
            breadcrumbs: ['库存管理', '库存单据', '移库单', '查看移库单'],
            openKeys: ['m4', 'm4-m1'],
          },
        },
  {
          path: 'inventory/stock-transfers/edit/:id',
          name: 'StockTransferEdit',
          component: () => import('@/views/inventory/stock-transfer-create.vue'),
          meta: {
            title: '编辑移库单',
            activeMenu: '/inventory/stock-transfers',
            breadcrumbs: ['库存管理', '库存单据', '移库单', '编辑移库单'],
            openKeys: ['m4', 'm4-m1'],
          },
        },
  {
          path: 'inventory/stock-transfer-inbounds/create',
          name: 'StockTransferInboundCreate',
          component: () => import('@/views/inventory/stock-transfer-inbound-create.vue'),
          meta: {
            title: '新增移库入库',
            activeMenu: '/inventory/stock-transfer-inbounds',
            breadcrumbs: ['库存管理', '库存单据', '移库入库', '新增移库入库'],
            openKeys: ['m4', 'm4-m1'],
          },
        },
  {
          path: 'inventory/stock-transfer-inbounds/view/:id',
          name: 'StockTransferInboundView',
          component: () => import('@/views/inventory/stock-transfer-inbound-create.vue'),
          meta: {
            title: '查看移库入库',
            activeMenu: '/inventory/stock-transfer-inbounds',
            breadcrumbs: ['库存管理', '库存单据', '移库入库', '查看移库入库'],
            openKeys: ['m4', 'm4-m1'],
          },
        },
  {
          path: 'inventory/stock-transfer-inbounds/edit/:id',
          name: 'StockTransferInboundEdit',
          component: () => import('@/views/inventory/stock-transfer-inbound-create.vue'),
          meta: {
            title: '编辑移库入库',
            activeMenu: '/inventory/stock-transfer-inbounds',
            breadcrumbs: ['库存管理', '库存单据', '移库入库', '编辑移库入库'],
            openKeys: ['m4', 'm4-m1'],
          },
        },
  {
          path: 'inventory/department-transfers/create',
          name: 'DepartmentTransferCreate',
          component: () => import('@/views/inventory/department-transfer-create.vue'),
          meta: {
            title: '新增部门调拨',
            activeMenu: '/inventory/department-transfers',
            breadcrumbs: ['库存管理', '库存单据', '部门调拨', '新增部门调拨'],
            openKeys: ['m4', 'm4-m1'],
          },
        },
  {
          path: 'inventory/department-transfers/view/:id',
          name: 'DepartmentTransferView',
          component: () => import('@/views/inventory/department-transfer-create.vue'),
          meta: {
            title: '查看部门调拨',
            activeMenu: '/inventory/department-transfers',
            breadcrumbs: ['库存管理', '库存单据', '部门调拨', '查看部门调拨'],
            openKeys: ['m4', 'm4-m1'],
          },
        },
  {
          path: 'inventory/department-transfers/edit/:id',
          name: 'DepartmentTransferEdit',
          component: () => import('@/views/inventory/department-transfer-create.vue'),
          meta: {
            title: '编辑部门调拨',
            activeMenu: '/inventory/department-transfers',
            breadcrumbs: ['库存管理', '库存单据', '部门调拨', '编辑部门调拨'],
            openKeys: ['m4', 'm4-m1'],
          },
        },
  {
          path: 'inventory/store-transfers/create',
          name: 'StoreTransferOutboundCreate',
          component: () => import('@/views/inventory/store-transfer-outbound-create.vue'),
          meta: {
            title: '新增店间调拨（调出）',
            activeMenu: '/inventory/store-transfers',
            breadcrumbs: ['库存管理', '库存单据', '店间调拨', '新增店间调拨（调出）'],
            openKeys: ['m4', 'm4-m1'],
          },
        },
  {
          path: 'inventory/store-transfers/view/:id',
          name: 'StoreTransferOutboundView',
          component: () => import('@/views/inventory/store-transfer-outbound-create.vue'),
          meta: {
            title: '查看店间调拨（调出）',
            activeMenu: '/inventory/store-transfers',
            breadcrumbs: ['库存管理', '库存单据', '店间调拨', '查看店间调拨（调出）'],
            openKeys: ['m4', 'm4-m1'],
          },
        },
  {
          path: 'inventory/store-transfers/edit/:id',
          name: 'StoreTransferOutboundEdit',
          component: () => import('@/views/inventory/store-transfer-outbound-create.vue'),
          meta: {
            title: '编辑店间调拨（调出）',
            activeMenu: '/inventory/store-transfers',
            breadcrumbs: ['库存管理', '库存单据', '店间调拨', '编辑店间调拨（调出）'],
            openKeys: ['m4', 'm4-m1'],
          },
        },
  {
          path: 'inventory/damage-outbounds/create',
          name: 'DamageOutboundCreate',
          component: () => import('@/views/inventory/damage-outbound-create.vue'),
          meta: {
            title: '新增报损出库',
            activeMenu: '/inventory/damage-outbounds',
            breadcrumbs: ['库存管理', '库存单据', '报损出库', '新增报损出库'],
            openKeys: ['m4', 'm4-m1'],
          },
        },
  {
          path: 'inventory/damage-outbounds/view/:id',
          name: 'DamageOutboundView',
          component: () => import('@/views/inventory/damage-outbound-create.vue'),
          meta: {
            title: '查看报损出库',
            activeMenu: '/inventory/damage-outbounds',
            breadcrumbs: ['库存管理', '库存单据', '报损出库', '查看报损出库'],
            openKeys: ['m4', 'm4-m1'],
          },
        },
  {
          path: 'inventory/damage-outbounds/edit/:id',
          name: 'DamageOutboundEdit',
          component: () => import('@/views/inventory/damage-outbound-create.vue'),
          meta: {
            title: '编辑报损出库',
            activeMenu: '/inventory/damage-outbounds',
            breadcrumbs: ['库存管理', '库存单据', '报损出库', '编辑报损出库'],
            openKeys: ['m4', 'm4-m1'],
          },
        },
  {
          path: 'inventory/other-inbounds/create',
          name: 'OtherInboundCreate',
          component: () => import('@/views/inventory/other-inbound-create.vue'),
          meta: {
            title: '新增其他入库',
            activeMenu: '/inventory/other-inbounds',
            breadcrumbs: ['库存管理', '库存单据', '其他入库', '新增其他入库'],
            openKeys: ['m4', 'm4-m1'],
          },
        },
  {
          path: 'inventory/other-inbounds/view/:id',
          name: 'OtherInboundView',
          component: () => import('@/views/inventory/other-inbound-create.vue'),
          meta: {
            title: '查看其他入库',
            activeMenu: '/inventory/other-inbounds',
            breadcrumbs: ['库存管理', '库存单据', '其他入库', '查看其他入库'],
            openKeys: ['m4', 'm4-m1'],
          },
        },
  {
          path: 'inventory/other-inbounds/edit/:id',
          name: 'OtherInboundEdit',
          component: () => import('@/views/inventory/other-inbound-create.vue'),
          meta: {
            title: '编辑其他入库',
            activeMenu: '/inventory/other-inbounds',
            breadcrumbs: ['库存管理', '库存单据', '其他入库', '编辑其他入库'],
            openKeys: ['m4', 'm4-m1'],
          },
        },
  {
          path: 'inventory/other-outbounds/create',
          name: 'OtherOutboundCreate',
          component: () => import('@/views/inventory/other-outbound-create.vue'),
          meta: {
            title: '新增其他出库',
            activeMenu: '/inventory/other-outbounds',
            breadcrumbs: ['库存管理', '库存单据', '其他出库', '新增其他出库'],
            openKeys: ['m4', 'm4-m1'],
          },
        },
  {
          path: 'inventory/other-outbounds/view/:id',
          name: 'OtherOutboundView',
          component: () => import('@/views/inventory/other-outbound-create.vue'),
          meta: {
            title: '查看其他出库',
            activeMenu: '/inventory/other-outbounds',
            breadcrumbs: ['库存管理', '库存单据', '其他出库', '查看其他出库'],
            openKeys: ['m4', 'm4-m1'],
          },
        },
  {
          path: 'inventory/other-outbounds/edit/:id',
          name: 'OtherOutboundEdit',
          component: () => import('@/views/inventory/other-outbound-create.vue'),
          meta: {
            title: '编辑其他出库',
            activeMenu: '/inventory/other-outbounds',
            breadcrumbs: ['库存管理', '库存单据', '其他出库', '编辑其他出库'],
            openKeys: ['m4', 'm4-m1'],
          },
        },
  {
          path: 'inventory/production-inbounds/create',
          name: 'ProductionInboundCreate',
          component: () => import('@/views/inventory/production-inbound-create.vue'),
          meta: {
            title: '新增生产入库',
            activeMenu: '/inventory/production-inbounds',
            breadcrumbs: ['库存管理', '库存单据', '生产入库', '新增生产入库'],
            openKeys: ['m4', 'm4-m1'],
          },
        },
  {
          path: 'inventory/production-inbounds/view/:id',
          name: 'ProductionInboundView',
          component: () => import('@/views/inventory/production-inbound-create.vue'),
          meta: {
            title: '查看生产入库',
            activeMenu: '/inventory/production-inbounds',
            breadcrumbs: ['库存管理', '库存单据', '生产入库', '查看生产入库'],
            openKeys: ['m4', 'm4-m1'],
          },
        },
  {
          path: 'inventory/production-inbounds/edit/:id',
          name: 'ProductionInboundEdit',
          component: () => import('@/views/inventory/production-inbound-create.vue'),
          meta: {
            title: '编辑生产入库',
            activeMenu: '/inventory/production-inbounds',
            breadcrumbs: ['库存管理', '库存单据', '生产入库', '编辑生产入库'],
            openKeys: ['m4', 'm4-m1'],
          },
        },
  {
          path: 'inventory/customer-sales-outbounds/create',
          name: 'CustomerSalesOutboundCreate',
          component: () => import('@/views/inventory/customer-sales-outbound-create.vue'),
          meta: {
            title: '新增客户销售出库',
            activeMenu: '/inventory/customer-sales-outbounds',
            breadcrumbs: ['库存管理', '库存单据', '客户销售出库', '新增客户销售出库'],
            openKeys: ['m4', 'm4-m1'],
          },
        },
  {
          path: 'inventory/customer-sales-outbounds/view/:id',
          name: 'CustomerSalesOutboundView',
          component: () => import('@/views/inventory/customer-sales-outbound-create.vue'),
          meta: {
            title: '查看客户销售出库',
            activeMenu: '/inventory/customer-sales-outbounds',
            breadcrumbs: ['库存管理', '库存单据', '客户销售出库', '查看客户销售出库'],
            openKeys: ['m4', 'm4-m1'],
          },
        },
  {
          path: 'inventory/customer-sales-outbounds/edit/:id',
          name: 'CustomerSalesOutboundEdit',
          component: () => import('@/views/inventory/customer-sales-outbound-create.vue'),
          meta: {
            title: '编辑客户销售出库',
            activeMenu: '/inventory/customer-sales-outbounds',
            breadcrumbs: ['库存管理', '库存单据', '客户销售出库', '编辑客户销售出库'],
            openKeys: ['m4', 'm4-m1'],
          },
        },
  {
          path: 'inventory/dish-consumption-outbounds/create',
          name: 'DishConsumptionOutboundCreate',
          component: () => import('@/views/inventory/dish-consumption-outbound-create.vue'),
          meta: {
            title: '新增菜品消耗出库',
            activeMenu: '/inventory/dish-consumption-outbounds',
            breadcrumbs: ['库存管理', '库存单据', '菜品消耗出库', '新增菜品消耗出库'],
            openKeys: ['m4', 'm4-m1'],
          },
        },
  {
          path: 'inventory/dish-consumption-outbounds/view/:id',
          name: 'DishConsumptionOutboundView',
          component: () => import('@/views/inventory/dish-consumption-outbound-create.vue'),
          meta: {
            title: '查看菜品消耗出库',
            activeMenu: '/inventory/dish-consumption-outbounds',
            breadcrumbs: ['库存管理', '库存单据', '菜品消耗出库', '查看菜品消耗出库'],
            openKeys: ['m4', 'm4-m1'],
          },
        },
  {
          path: 'inventory/dish-consumption-outbounds/edit/:id',
          name: 'DishConsumptionOutboundEdit',
          component: () => import('@/views/inventory/dish-consumption-outbound-create.vue'),
          meta: {
            title: '编辑菜品消耗出库',
            activeMenu: '/inventory/dish-consumption-outbounds',
            breadcrumbs: ['库存管理', '库存单据', '菜品消耗出库', '编辑菜品消耗出库'],
            openKeys: ['m4', 'm4-m1'],
          },
        },
  {
          path: 'inventory/customer-return-inbounds/create',
          name: 'CustomerReturnInboundCreate',
          component: () => import('@/views/inventory/customer-return-inbound-create.vue'),
          meta: {
            title: '新增客户退货入库',
            activeMenu: '/inventory/customer-return-inbounds',
            breadcrumbs: ['库存管理', '库存单据', '客户退货入库', '新增客户退货入库'],
            openKeys: ['m4', 'm4-m1'],
          },
        },
  {
          path: 'inventory/customer-return-inbounds/view/:id',
          name: 'CustomerReturnInboundView',
          component: () => import('@/views/inventory/customer-return-inbound-create.vue'),
          meta: {
            title: '查看客户退货入库',
            activeMenu: '/inventory/customer-return-inbounds',
            breadcrumbs: ['库存管理', '库存单据', '客户退货入库', '查看客户退货入库'],
            openKeys: ['m4', 'm4-m1'],
          },
        },
  {
          path: 'inventory/customer-return-inbounds/edit/:id',
          name: 'CustomerReturnInboundEdit',
          component: () => import('@/views/inventory/customer-return-inbound-create.vue'),
          meta: {
            title: '编辑客户退货入库',
            activeMenu: '/inventory/customer-return-inbounds',
            breadcrumbs: ['库存管理', '库存单据', '客户退货入库', '编辑客户退货入库'],
            openKeys: ['m4', 'm4-m1'],
          },
        },
  {
          path: 'inventory/stock-transfer-outbounds/create',
          name: 'StockTransferOutboundCreate',
          component: () => import('@/views/inventory/stock-transfer-outbound-create.vue'),
          meta: {
            title: '新增移库出库',
            activeMenu: '/inventory/stock-transfer-outbounds',
            breadcrumbs: ['库存管理', '库存单据', '移库出库', '新增移库出库'],
            openKeys: ['m4', 'm4-m1'],
          },
        },
  {
          path: 'inventory/stock-transfer-outbounds/view/:id',
          name: 'StockTransferOutboundView',
          component: () => import('@/views/inventory/stock-transfer-outbound-create.vue'),
          meta: {
            title: '查看移库出库',
            activeMenu: '/inventory/stock-transfer-outbounds',
            breadcrumbs: ['库存管理', '库存单据', '移库出库', '查看移库出库'],
            openKeys: ['m4', 'm4-m1'],
          },
        },
  {
          path: 'inventory/stock-transfer-outbounds/edit/:id',
          name: 'StockTransferOutboundEdit',
          component: () => import('@/views/inventory/stock-transfer-outbound-create.vue'),
          meta: {
            title: '编辑移库出库',
            activeMenu: '/inventory/stock-transfer-outbounds',
            breadcrumbs: ['库存管理', '库存单据', '移库出库', '编辑移库出库'],
            openKeys: ['m4', 'm4-m1'],
          },
        },
  {
          path: 'inventory/inventory-checks/create',
          name: 'InventoryCheckCreate',
          component: () => import('@/views/inventory/inventory-check-create.vue'),
          meta: {
            title: '新增盘点单',
            activeMenu: '/inventory/inventory-checks',
            breadcrumbs: ['库存管理', '盘点管理', '盘点单', '新增盘点单'],
            openKeys: ['m4', 'm4-m2'],
          },
        },
  {
          path: 'inventory/inventory-checks',
          name: 'InventoryCheckIndex',
          component: () => import('@/views/inventory/inventory-check.vue'),
          meta: {
            title: '盘点单',
            activeMenu: '/inventory/inventory-checks',
            breadcrumbs: ['库存管理', '盘点管理', '盘点单'],
            openKeys: ['m4', 'm4-m2'],
          },
        },
  {
          path: 'inventory/inventory-checks/view/:id',
          name: 'InventoryCheckView',
          component: () => import('@/views/inventory/inventory-check-create.vue'),
          meta: {
            title: '查看盘点单',
            activeMenu: '/inventory/inventory-checks',
            breadcrumbs: ['库存管理', '盘点管理', '盘点单', '查看盘点单'],
            openKeys: ['m4', 'm4-m2'],
          },
        },
  {
          path: 'inventory/multi-inventory-checks',
          name: 'MultiInventoryCheckIndex',
          component: () => import('@/views/inventory/multi-inventory-check.vue'),
          meta: {
            title: '多人盘点单',
            activeMenu: '/inventory/multi-inventory-checks',
            breadcrumbs: ['库存管理', '盘点管理', '多人盘点单'],
            openKeys: ['m4', 'm4-m2'],
          },
        },
  {
          path: 'inventory/inventory-checks/edit/:id',
          name: 'InventoryCheckEdit',
          component: () => import('@/views/inventory/inventory-check-create.vue'),
          meta: {
            title: '编辑盘点单',
            activeMenu: '/inventory/inventory-checks',
            breadcrumbs: ['库存管理', '盘点管理', '盘点单', '编辑盘点单'],
            openKeys: ['m4', 'm4-m2'],
          },
        },
  {
          path: 'inventory/inventory-templates/create',
          name: 'InventoryTemplateCreate',
          component: () => import('@/views/inventory/inventory-template-create.vue'),
          meta: {
            title: '新增库存模板',
            activeMenu: '/inventory/inventory-templates',
            breadcrumbs: ['库存管理', '库存规则', '库存模板', '新增库存模板'],
            openKeys: ['m4', 'm4-m5'],
          },
        }
];
