import type { RouteRecordRaw } from 'vue-router';

export const purchaseRoutes: RouteRecordRaw[] = [
  {
          path: 'purchase/pricing/create',
          name: 'PurchasePricingCreate',
          component: () => import('@/views/purchase/pricing-create.vue'),
          meta: {
            title: '新增采购单定价',
            activeMenu: '/purchase/pricing',
            breadcrumbs: ['采购管理', '价格管理', '采购单定价', '新增采购单定价'],
            openKeys: ['m2', 'm2-m1'],
          },
        },
  {
          path: 'purchase/applications/create',
          name: 'PurchaseApplicationCreate',
          component: () => import('@/views/purchase/purchase-document-create.vue'),
          meta: {
            title: '新增采购单申请',
            activeMenu: '/purchase/applications',
            breadcrumbs: ['采购管理', '单据', '采购单申请', '新增采购单申请'],
            openKeys: ['m2', 'm2-m2'],
            purchaseDocumentType: 'applications',
            purchaseDocumentMode: 'create',
          },
        },
  {
          path: 'purchase/applications/view/:id',
          name: 'PurchaseApplicationView',
          component: () => import('@/views/purchase/purchase-document-create.vue'),
          meta: {
            title: '查看采购单申请',
            activeMenu: '/purchase/applications',
            breadcrumbs: ['采购管理', '单据', '采购单申请', '查看采购单申请'],
            openKeys: ['m2', 'm2-m2'],
            purchaseDocumentType: 'applications',
            purchaseDocumentMode: 'view',
          },
        },
  {
          path: 'purchase/applications/edit/:id',
          name: 'PurchaseApplicationEdit',
          component: () => import('@/views/purchase/purchase-document-create.vue'),
          meta: {
            title: '编辑采购单申请',
            activeMenu: '/purchase/applications',
            breadcrumbs: ['采购管理', '单据', '采购单申请', '编辑采购单申请'],
            openKeys: ['m2', 'm2-m2'],
            purchaseDocumentType: 'applications',
            purchaseDocumentMode: 'edit',
          },
        },
  {
          path: 'purchase/orders/create',
          name: 'PurchaseOrderCreate',
          component: () => import('@/views/purchase/purchase-document-create.vue'),
          meta: {
            title: '新增采购订单',
            activeMenu: '/purchase/orders',
            breadcrumbs: ['采购管理', '单据', '采购订单', '新增采购订单'],
            openKeys: ['m2', 'm2-m2'],
            purchaseDocumentType: 'orders',
            purchaseDocumentMode: 'create',
          },
        },
  {
          path: 'purchase/orders/view/:id',
          name: 'PurchaseOrderView',
          component: () => import('@/views/purchase/purchase-document-create.vue'),
          meta: {
            title: '查看采购订单',
            activeMenu: '/purchase/orders',
            breadcrumbs: ['采购管理', '单据', '采购订单', '查看采购订单'],
            openKeys: ['m2', 'm2-m2'],
            purchaseDocumentType: 'orders',
            purchaseDocumentMode: 'view',
          },
        },
  {
          path: 'purchase/orders/edit/:id',
          name: 'PurchaseOrderEdit',
          component: () => import('@/views/purchase/purchase-document-create.vue'),
          meta: {
            title: '编辑采购订单',
            activeMenu: '/purchase/orders',
            breadcrumbs: ['采购管理', '单据', '采购订单', '编辑采购订单'],
            openKeys: ['m2', 'm2-m2'],
            purchaseDocumentType: 'orders',
            purchaseDocumentMode: 'edit',
          },
        },
  {
          path: 'purchase/receipts/create',
          name: 'PurchaseReceiptCreate',
          component: () => import('@/views/purchase/purchase-document-create.vue'),
          meta: {
            title: '新增采购收货',
            activeMenu: '/purchase/receipts',
            breadcrumbs: ['采购管理', '单据', '采购收货', '新增采购收货'],
            openKeys: ['m2', 'm2-m2'],
            purchaseDocumentType: 'receipts',
            purchaseDocumentMode: 'create',
          },
        },
  {
          path: 'purchase/receipts/view/:id',
          name: 'PurchaseReceiptView',
          component: () => import('@/views/purchase/purchase-document-create.vue'),
          meta: {
            title: '查看采购收货',
            activeMenu: '/purchase/receipts',
            breadcrumbs: ['采购管理', '单据', '采购收货', '查看采购收货'],
            openKeys: ['m2', 'm2-m2'],
            purchaseDocumentType: 'receipts',
            purchaseDocumentMode: 'view',
          },
        },
  {
          path: 'purchase/receipts/edit/:id',
          name: 'PurchaseReceiptEdit',
          component: () => import('@/views/purchase/purchase-document-create.vue'),
          meta: {
            title: '编辑采购收货',
            activeMenu: '/purchase/receipts',
            breadcrumbs: ['采购管理', '单据', '采购收货', '编辑采购收货'],
            openKeys: ['m2', 'm2-m2'],
            purchaseDocumentType: 'receipts',
            purchaseDocumentMode: 'edit',
          },
        },
  {
          path: 'purchase/returns/create',
          name: 'PurchaseReturnCreate',
          component: () => import('@/views/purchase/purchase-document-create.vue'),
          meta: {
            title: '新增采购退货',
            activeMenu: '/purchase/returns',
            breadcrumbs: ['采购管理', '单据', '采购退货', '新增采购退货'],
            openKeys: ['m2', 'm2-m2'],
            purchaseDocumentType: 'returns',
            purchaseDocumentMode: 'create',
          },
        },
  {
          path: 'purchase/returns/view/:id',
          name: 'PurchaseReturnView',
          component: () => import('@/views/purchase/purchase-document-create.vue'),
          meta: {
            title: '查看采购退货',
            activeMenu: '/purchase/returns',
            breadcrumbs: ['采购管理', '单据', '采购退货', '查看采购退货'],
            openKeys: ['m2', 'm2-m2'],
            purchaseDocumentType: 'returns',
            purchaseDocumentMode: 'view',
          },
        },
  {
          path: 'purchase/returns/edit/:id',
          name: 'PurchaseReturnEdit',
          component: () => import('@/views/purchase/purchase-document-create.vue'),
          meta: {
            title: '编辑采购退货',
            activeMenu: '/purchase/returns',
            breadcrumbs: ['采购管理', '单据', '采购退货', '编辑采购退货'],
            openKeys: ['m2', 'm2-m2'],
            purchaseDocumentType: 'returns',
            purchaseDocumentMode: 'edit',
          },
        }
];
