import type { CategoryNode, SupplierQuery, SupplierRow, SupplierTableColumn } from './types';

export const defaultSupplierQuery: SupplierQuery = {
  supplierInfo: '',
  status: '全部',
  bindStatus: '全部',
  source: '全部',
  supplyRelation: '全部',
};

export const statusOptions = ['全部', '启用', '停用'];
export const bindStatusOptions = ['全部', '已绑定', '未绑定'];
export const sourceOptions = ['全部', '集团', '门店'];
export const supplyRelationOptions = ['全部', '有', '无'];

export const supplierToolbarButtons = [
  '新增',
  '批量新增',
  '批量修改',
  '批量导入',
  '批量导出',
  '批量启用',
  '批量停用',
  '批量删除',
  '批量注册绑定',
];

export const supplierInfoTree: CategoryNode[] = [
  {
    id: '全部供应商',
    label: '全部供应商',
    children: [
      {
        id: '食材供应商',
        label: '食材供应商',
        children: [
          { id: '生鲜类', label: '生鲜类' },
          { id: '干货类', label: '干货类' },
        ],
      },
      {
        id: '服务供应商',
        label: '服务供应商',
        children: [
          { id: '物流服务', label: '物流服务' },
          { id: '设备维保', label: '设备维保' },
        ],
      },
    ],
  },
];

export const supplierCategoryTree: CategoryNode[] = [
  {
    id: 'all',
    label: '供应商类别',
    children: [
      { id: '生鲜类', label: '生鲜类' },
      { id: '干货类', label: '干货类' },
      { id: '物流服务', label: '物流服务' },
      { id: '设备维保', label: '设备维保' },
    ],
  },
];

export const supplierColumns: SupplierTableColumn[] = [
  { prop: 'index', label: '序号', width: 56, fixed: 'left' },
  { prop: 'supplierCode', label: '供应商编码', width: 110, fixed: 'left' },
  { prop: 'supplierName', label: '供应商名称', width: 140, fixed: 'left' },
  { prop: 'supplierCategory', label: '供应商类别', width: 104 },
  { prop: 'contactPerson', label: '联系人', width: 92 },
  { prop: 'contactPhone', label: '联系电话', width: 120 },
  { prop: 'settlementMethod', label: '结算方式', width: 92 },
  { prop: 'source', label: '来源', width: 72 },
  { prop: 'supplyRelation', label: '供货关系', width: 80 },
  { prop: 'remark', label: '备注', width: 160 },
  { prop: 'status', label: '启用状态', width: 80 },
  { prop: 'operatedAt', label: '操作时间', width: 148 },
];

export const supplierData: SupplierRow[] = [
  {
    id: 1,
    index: 1,
    supplierCode: 'SUP-0001',
    supplierName: '青禾生鲜配送',
    supplierCategory: '生鲜类',
    contactPerson: '张伟',
    contactPhone: '13800138001',
    settlementMethod: '月结',
    source: '集团',
    supplyRelation: '有',
    remark: '蔬菜日配',
    status: '启用',
    bindStatus: '已绑定',
    operatedAt: '2026-04-10 10:22:18',
  },
  {
    id: 2,
    index: 2,
    supplierCode: 'SUP-0002',
    supplierName: '海泽水产',
    supplierCategory: '生鲜类',
    contactPerson: '李明',
    contactPhone: '13800138002',
    settlementMethod: '半月结',
    source: '门店',
    supplyRelation: '有',
    remark: '海鲜类',
    status: '启用',
    bindStatus: '未绑定',
    operatedAt: '2026-04-09 18:16:40',
  },
  {
    id: 3,
    index: 3,
    supplierCode: 'SUP-0003',
    supplierName: '宏源干货',
    supplierCategory: '干货类',
    contactPerson: '王芳',
    contactPhone: '13800138003',
    settlementMethod: '月结',
    source: '集团',
    supplyRelation: '有',
    remark: '干货调料',
    status: '停用',
    bindStatus: '已绑定',
    operatedAt: '2026-04-08 15:10:09',
  },
  {
    id: 4,
    index: 4,
    supplierCode: 'SUP-0004',
    supplierName: '佳味粮油',
    supplierCategory: '干货类',
    contactPerson: '赵雷',
    contactPhone: '13800138004',
    settlementMethod: '现结',
    source: '门店',
    supplyRelation: '无',
    remark: '暂停合作',
    status: '停用',
    bindStatus: '未绑定',
    operatedAt: '2026-04-07 09:05:33',
  },
  {
    id: 5,
    index: 5,
    supplierCode: 'SUP-0005',
    supplierName: '迅达物流',
    supplierCategory: '物流服务',
    contactPerson: '陈涛',
    contactPhone: '13800138005',
    settlementMethod: '月结',
    source: '集团',
    supplyRelation: '有',
    remark: '干线运输',
    status: '启用',
    bindStatus: '已绑定',
    operatedAt: '2026-04-06 12:11:19',
  },
  {
    id: 6,
    index: 6,
    supplierCode: 'SUP-0006',
    supplierName: '安诚设备维保',
    supplierCategory: '设备维保',
    contactPerson: '周楠',
    contactPhone: '13800138006',
    settlementMethod: '季结',
    source: '集团',
    supplyRelation: '无',
    remark: '待签合同',
    status: '启用',
    bindStatus: '未绑定',
    operatedAt: '2026-04-05 20:40:02',
  },
  {
    id: 7,
    index: 7,
    supplierCode: 'SUP-0007',
    supplierName: '惠农果蔬',
    supplierCategory: '生鲜类',
    contactPerson: '冯杰',
    contactPhone: '13800138007',
    settlementMethod: '月结',
    source: '门店',
    supplyRelation: '有',
    remark: '水果类',
    status: '启用',
    bindStatus: '已绑定',
    operatedAt: '2026-04-05 10:04:11',
  },
  {
    id: 8,
    index: 8,
    supplierCode: 'SUP-0008',
    supplierName: '百川调味',
    supplierCategory: '干货类',
    contactPerson: '高琳',
    contactPhone: '13800138008',
    settlementMethod: '现结',
    source: '门店',
    supplyRelation: '有',
    remark: '复合调味料',
    status: '启用',
    bindStatus: '未绑定',
    operatedAt: '2026-04-04 16:37:55',
  },
  {
    id: 9,
    index: 9,
    supplierCode: 'SUP-0009',
    supplierName: '顺恒冷链',
    supplierCategory: '物流服务',
    contactPerson: '许洋',
    contactPhone: '13800138009',
    settlementMethod: '月结',
    source: '集团',
    supplyRelation: '有',
    remark: '冷链配送',
    status: '停用',
    bindStatus: '已绑定',
    operatedAt: '2026-04-03 11:50:27',
  },
  {
    id: 10,
    index: 10,
    supplierCode: 'SUP-0010',
    supplierName: '德信餐具',
    supplierCategory: '设备维保',
    contactPerson: '朱敏',
    contactPhone: '13800138010',
    settlementMethod: '现结',
    source: '门店',
    supplyRelation: '无',
    remark: '一次性餐具',
    status: '启用',
    bindStatus: '未绑定',
    operatedAt: '2026-04-02 09:44:08',
  },
];
