BEGIN;

SELECT format(
    'COMMENT ON TABLE %I.%I IS %L;',
    n.nspname,
    c.relname,
    CASE
        WHEN c.relname = 'supplier_category' THEN '供应商类别表'
        WHEN c.relname LIKE 'inventory_%_line' THEN replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(replace(c.relname,
            'inventory_purchase_return_outbound_line', '采购退货单明细'),
            'inventory_customer_return_inbound_line', '客户退货入库单明细'),
            'inventory_customer_sales_outbound_line', '客户销售出库单明细'),
            'inventory_damage_outbound_line', '报损出库单明细'),
            'inventory_department_picking_line', '部门领料单明细'),
            'inventory_department_return_line', '部门退料单明细'),
            'inventory_department_transfer_line', '部门调拨单明细'),
            'inventory_dish_consumption_outbound_line', '菜品消耗出库单明细'),
            'inventory_other_inbound_line', '其他入库单明细'),
            'inventory_other_outbound_line', '其他出库单明细'),
            'inventory_production_inbound_line', '生产入库单明细'),
            'inventory_stock_transfer_inbound_line', '移库入库单明细'),
            'inventory_stock_transfer_line', '移库单明细'),
            'inventory_stock_transfer_outbound_line', '移库出库单明细'),
            'inventory_store_transfer_line', '店间调拨单明细'),
            'inventory_warehouse_opening_balance_line', '仓库期初单明细')
        WHEN c.relname = 'act_evt_log' THEN 'Flowable 事件日志表'
        WHEN c.relname LIKE 'act_ge_%' THEN 'Flowable 通用数据表'
        WHEN c.relname LIKE 'act_hi_%' THEN 'Flowable 历史数据表'
        WHEN c.relname LIKE 'act_id_%' THEN 'Flowable 身份数据表'
        WHEN c.relname LIKE 'act_re_%' THEN 'Flowable 流程定义数据表'
        WHEN c.relname LIKE 'act_ru_%' THEN 'Flowable 运行时数据表'
        WHEN c.relname LIKE 'act_%' THEN 'Flowable 流程引擎数据表'
        WHEN c.relname LIKE 'flw_%' THEN 'Flowable 事件引擎数据表'
        ELSE '业务数据表：' || c.relname
    END
)
FROM pg_class c
JOIN pg_namespace n ON n.oid = c.relnamespace
WHERE n.nspname = 'dev'
  AND c.relkind = 'r'
  AND coalesce(obj_description(c.oid, 'pg_class'), '') = ''
\gexec

SELECT format(
    'COMMENT ON COLUMN %I.%I.%I IS %L;',
    c.table_schema,
    c.table_name,
    c.column_name,
    CASE
        WHEN c.column_name = 'id' THEN '主键ID'
        WHEN c.column_name = 'id_' THEN '主键ID'
        WHEN c.column_name = 'rev_' THEN '版本号'
        WHEN c.column_name = 'created_at' THEN '创建时间'
        WHEN c.column_name = 'updated_at' THEN '更新时间'
        WHEN c.column_name = 'created_by' THEN '创建人'
        WHEN c.column_name = 'updated_by' THEN '最后修改人'
        WHEN c.column_name = 'status' THEN '状态'
        WHEN c.column_name = 'remark' THEN '备注'
        WHEN c.column_name IN ('sort_no', 'sort_order') THEN '排序号'
        WHEN c.column_name = 'scope_type' THEN '作用域类型：PLATFORM/GROUP/STORE'
        WHEN c.column_name = 'scope_id' THEN '作用域ID，PLATFORM 固定为 0'
        WHEN c.column_name = 'group_id' THEN '集团ID'
        WHEN c.column_name = 'store_id' THEN '门店ID'
        WHEN c.column_name = 'warehouse_id' THEN '仓库ID'
        WHEN c.column_name = 'warehouse_name' THEN '仓库名称'
        WHEN c.column_name = 'warehouse_code' THEN '仓库编码'
        WHEN c.column_name = 'supplier_id' THEN '供应商ID'
        WHEN c.column_name = 'supplier_code' THEN '供应商编码'
        WHEN c.column_name = 'supplier_name' THEN '供应商名称'
        WHEN c.column_name = 'item_id' THEN '物品ID'
        WHEN c.column_name = 'item_code' THEN '物品编码'
        WHEN c.column_name = 'item_name' THEN '物品名称'
        WHEN c.column_name = 'item_category' THEN '物品类别'
        WHEN c.column_name = 'spec' THEN '规格'
        WHEN c.column_name = 'spec_model' THEN '规格型号'
        WHEN c.column_name = 'unit' THEN '单位'
        WHEN c.column_name = 'base_unit' THEN '基准单位'
        WHEN c.column_name = 'purchase_unit' THEN '采购单位'
        WHEN c.column_name IN ('quantity', 'qty') THEN '数量'
        WHEN c.column_name = 'amount' THEN '金额'
        WHEN c.column_name = 'tax_rate' THEN '税率'
        WHEN c.column_name = 'unit_price' THEN '单价'
        WHEN c.column_name = 'document_id' THEN '单据ID'
        WHEN c.column_name = 'header_id' THEN '单头ID'
        WHEN c.column_name = 'document_code' THEN '单据编号'
        WHEN c.column_name = 'document_type' THEN '单据类型'
        WHEN c.column_name = 'document_status' THEN '单据状态'
        WHEN c.column_name = 'business_date' THEN '业务日期'
        WHEN c.column_name = 'audit_status' THEN '审核状态'
        WHEN c.column_name = 'audited_at' THEN '审核时间'
        WHEN c.column_name = 'audited_by' THEN '审核人'
        WHEN c.column_name = 'extra_json' THEN '扩展字段JSON'
        WHEN c.column_name = 'tenant_id' THEN '租户ID'
        WHEN c.column_name = 'builtin' THEN '是否系统内置'
        WHEN c.column_name = 'phone' THEN '手机号'
        WHEN c.column_name = 'email' THEN '邮箱'
        WHEN c.column_name = 'address' THEN '地址'
        WHEN c.column_name IN ('contact_name', 'contact_person') THEN '联系人'
        WHEN c.column_name = 'contact_phone' THEN '联系电话'
        WHEN c.column_name = 'category_code' THEN '类别编码'
        WHEN c.column_name = 'category_name' THEN '类别名称'
        WHEN c.column_name = 'parent_category' THEN '上级类别'
        WHEN c.column_name = 'child_category' THEN '下级类别'
        WHEN c.column_name = 'category' THEN '分类'
        WHEN c.column_name = 'bank_account' THEN '银行账号'
        WHEN c.column_name = 'account_name' THEN '账户名称'
        WHEN c.column_name = 'bank_name' THEN '开户银行'
        WHEN c.column_name = 'default_account' THEN '是否默认账户'
        WHEN c.column_name = 'business_code' THEN '业务编码'
        WHEN c.column_name = 'business_name' THEN '业务名称'
        WHEN c.column_name = 'business_id' THEN '业务ID'
        WHEN c.column_name = 'workflow_code' THEN '流程编码'
        WHEN c.column_name = 'workflow_name' THEN '流程名称'
        WHEN c.column_name = 'workflow_status' THEN '流程状态'
        WHEN c.column_name IN ('process_definition_key', 'workflow_definition_key') THEN '流程定义Key'
        WHEN c.column_name IN ('process_definition_id', 'workflow_definition_id') THEN '流程定义ID'
        WHEN c.column_name = 'workflow_process_code' THEN '关联流程编码'
        WHEN c.column_name = 'workflow_instance_id' THEN '流程实例ID'
        WHEN c.column_name = 'workflow_task_id' THEN '当前待办任务ID'
        WHEN c.column_name = 'workflow_task_name' THEN '当前待办任务名称'
        WHEN c.column_name = 'pending_operation' THEN '待处理动作'
        WHEN c.column_name = 'rejection_reason' THEN '拒审原因'
        WHEN c.column_name = 'salesman_user_id' THEN '业务员用户ID'
        WHEN c.column_name = 'salesman_name' THEN '业务员名称'
        WHEN c.column_name = 'print_status' THEN '打印状态'
        WHEN c.column_name = 'item_count' THEN '物品数量'
        WHEN c.column_name = 'total_amount' THEN '总金额'
        WHEN c.column_name = 'total_qty' THEN '总数量'
        WHEN c.column_name = 'warehouse_type' THEN '仓库类型'
        WHEN c.column_name = 'is_default' THEN '是否默认'
        WHEN c.column_name = 'rule_id' THEN '规则ID'
        WHEN c.column_name = 'rule_code' THEN '规则编码'
        WHEN c.column_name = 'rule_name' THEN '规则名称'
        WHEN c.column_name = 'business_control' THEN '是否启用业务管控'
        WHEN c.column_name = 'control_order' THEN '管控适用机构订货'
        WHEN c.column_name = 'control_purchase_inbound' THEN '管控适用机构采购入库'
        WHEN c.column_name = 'control_transfer_inbound' THEN '管控适用机构调拨入库'
        WHEN c.column_name = 'dict_code' THEN '字典编码'
        WHEN c.column_name = 'dict_name' THEN '字典名称'
        WHEN c.column_name = 'dict_type_id' THEN '字典类型ID'
        WHEN c.column_name = 'item_key' THEN '稳定项键'
        WHEN c.column_name = 'item_label' THEN '展示文本'
        WHEN c.column_name = 'table_name' THEN '表名'
        WHEN c.column_name = 'column_name' THEN '字段名'
        WHEN c.column_name = 'log_nr_' THEN '日志序号'
        WHEN c.column_name = 'type_' THEN '类型'
        WHEN c.column_name LIKE '%proc_def_id_' THEN '流程定义ID'
        WHEN c.column_name LIKE '%proc_inst_id_' THEN '流程实例ID'
        WHEN c.column_name = 'execution_id_' THEN '执行实例ID'
        WHEN c.column_name = 'task_id_' THEN '任务ID'
        WHEN c.column_name = 'time_stamp_' THEN '时间戳'
        WHEN c.column_name = 'user_id_' THEN '用户ID'
        WHEN c.column_name = 'data_' THEN '数据内容'
        WHEN c.column_name = 'lock_owner_' THEN '锁定人'
        WHEN c.column_name = 'lock_time_' THEN '锁定时间'
        WHEN c.column_name = 'is_processed_' THEN '是否已处理'
        WHEN c.column_name = 'name_' THEN '名称'
        WHEN c.column_name = 'deployment_id_' THEN '部署ID'
        WHEN c.column_name = 'bytes_' THEN '二进制内容'
        WHEN c.column_name = 'generated_' THEN '是否自动生成'
        WHEN c.column_name = 'value_' THEN '属性值'
        WHEN c.column_name = 'act_id_' THEN '活动ID'
        WHEN c.column_name = 'act_name_' THEN '活动名称'
        WHEN c.column_name = 'act_type_' THEN '活动类型'
        WHEN c.column_name = 'assignee_' THEN '办理人'
        WHEN c.column_name = 'completed_by_' THEN '完成人'
        WHEN c.column_name = 'start_time_' THEN '开始时间'
        WHEN c.column_name = 'end_time_' THEN '结束时间'
        WHEN c.column_name = 'duration_' THEN '持续时长'
        WHEN c.column_name = 'delete_reason_' THEN '删除原因'
        WHEN c.column_name = 'tenant_id_' THEN '租户ID'
        WHEN c.column_name = 'description_' THEN '说明'
        WHEN c.column_name = 'url_' THEN '链接地址'
        WHEN c.column_name = 'content_id_' THEN '内容ID'
        WHEN c.column_name = 'time_' THEN '时间'
        WHEN c.column_name = 'action_' THEN '操作'
        WHEN c.column_name = 'message_' THEN '消息'
        WHEN c.column_name = 'full_msg_' THEN '完整消息'
        WHEN c.column_name = 'var_type_' THEN '变量类型'
        WHEN c.column_name = 'bytearray_id_' THEN '二进制资源ID'
        WHEN c.column_name IN ('double_', 'long_', 'text_', 'text2_') THEN '变量值'
        WHEN c.column_name LIKE '%scope_id_' THEN '范围ID'
        WHEN c.column_name LIKE '%scope_type_' THEN '范围类型'
        WHEN c.column_name LIKE '%scope_definition_id_' THEN '范围定义ID'
        WHEN c.column_name = 'group_id_' THEN '用户组ID'
        WHEN c.column_name = 'state_' THEN '状态'
        WHEN c.column_name = 'owner_' THEN '拥有人'
        WHEN c.column_name = 'priority_' THEN '优先级'
        WHEN c.column_name = 'due_date_' THEN '到期时间'
        WHEN c.column_name = 'form_key_' THEN '表单Key'
        WHEN c.column_name = 'last_updated_time_' THEN '最后更新时间'
        WHEN c.column_name = 'business_key_' THEN '业务键'
        WHEN c.column_name = 'start_user_id_' THEN '发起用户ID'
        WHEN c.column_name = 'callback_id_' THEN '回调ID'
        WHEN c.column_name = 'callback_type_' THEN '回调类型'
        WHEN c.column_name = 'reference_id_' THEN '引用ID'
        WHEN c.column_name = 'reference_type_' THEN '引用类型'
        WHEN c.column_name = 'business_status_' THEN '业务状态'
        WHEN c.column_name = 'meta_info_' THEN '元数据'
        WHEN c.column_name = 'key_' THEN '键'
        WHEN c.column_name = 'deploy_time_' THEN '部署时间'
        WHEN c.column_name = 'resource_name_' THEN '资源名称'
        WHEN c.column_name = 'version_' THEN '版本号'
        WHEN c.column_name = 'engine_version_' THEN '引擎版本'
        WHEN c.column_name = 'category_' THEN '分类'
        WHEN c.column_name = 'parent_id_' THEN '父级ID'
        WHEN c.column_name LIKE 'is_%_' THEN '是否' || replace(trim(both '_' from substring(c.column_name from 4)), '_', ' ')
        WHEN c.column_name = 'event_type_' THEN '事件类型'
        WHEN c.column_name = 'event_name_' THEN '事件名称'
        WHEN c.column_name = 'configuration_' THEN '配置'
        WHEN c.column_name = 'created_' THEN '创建时间'
        WHEN c.column_name = 'exclusive_' THEN '是否独占'
        WHEN c.column_name = 'process_instance_id_' THEN '流程实例ID'
        WHEN c.column_name = 'element_id_' THEN '元素ID'
        WHEN c.column_name = 'element_name_' THEN '元素名称'
        WHEN c.column_name = 'correlation_id_' THEN '关联ID'
        WHEN c.column_name = 'exception_stack_id_' THEN '异常堆栈资源ID'
        WHEN c.column_name = 'exception_msg_' THEN '异常消息'
        WHEN c.column_name = 'duedate_' THEN '到期时间'
        WHEN c.column_name = 'repeat_' THEN '重复表达式'
        WHEN c.column_name = 'handler_type_' THEN '处理器类型'
        WHEN c.column_name = 'handler_cfg_' THEN '处理器配置'
        WHEN c.column_name = 'custom_values_id_' THEN '自定义值资源ID'
        WHEN c.column_name = 'retries_' THEN '重试次数'
        WHEN c.column_name LIKE '%_id' THEN replace(left(c.column_name, length(c.column_name) - 3), '_', ' ') || ' ID'
        WHEN c.column_name LIKE '%_code' THEN replace(left(c.column_name, length(c.column_name) - 5), '_', ' ') || '编码'
        WHEN c.column_name LIKE '%_name' THEN replace(left(c.column_name, length(c.column_name) - 5), '_', ' ') || '名称'
        WHEN c.column_name LIKE '%_date' THEN replace(left(c.column_name, length(c.column_name) - 5), '_', ' ') || '日期'
        WHEN c.column_name LIKE '%_at' THEN replace(left(c.column_name, length(c.column_name) - 3), '_', ' ') || '时间'
        WHEN c.table_name LIKE 'act_%' OR c.table_name LIKE 'flw_%' THEN 'Flowable字段：' || c.column_name
        ELSE '业务字段：' || c.column_name
    END
)
FROM information_schema.columns c
WHERE c.table_schema = 'dev'
  AND coalesce(col_description(format('%I.%I', c.table_schema, c.table_name)::regclass::oid, c.ordinal_position), '') = ''
\gexec

COMMIT;
