-- ============================================================
-- 库存模块独立建表脚本
-- 来源: init.sql (第4861-5024行)
-- 用法: 在 PostgreSQL 中执行此脚本（使用 dev schema）
-- 执行前确认: SET search_path TO dev, public;
-- ============================================================

SET search_path TO dev, public;

-- -----------------------------------------------------------
-- 1. 采购入库单主表
-- -----------------------------------------------------------
CREATE TABLE IF NOT EXISTS inventory_purchase_inbound
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    scope_type     VARCHAR(16)   NOT NULL DEFAULT 'PLATFORM',
    scope_id       BIGINT        NOT NULL DEFAULT 0,
    document_code  VARCHAR(64)   NOT NULL,
    inbound_date   DATE          NOT NULL,
    warehouse_name VARCHAR(128)  NOT NULL,
    supplier_name  VARCHAR(128)  NOT NULL,
    upstream_code  VARCHAR(64),
    status         VARCHAR(16)   NOT NULL DEFAULT '草稿',
    remark         VARCHAR(500),
    created_by     BIGINT,
    approved_by    BIGINT,
    approved_at    TIMESTAMP,
    created_at     TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at     TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_inventory_purchase_inbound_scope_code UNIQUE (scope_type, scope_id, document_code),
    CONSTRAINT ck_inventory_purchase_inbound_scope_type CHECK (scope_type IN ('PLATFORM', 'GROUP', 'STORE'))
);

CREATE INDEX IF NOT EXISTS idx_inventory_purchase_inbound_scope ON inventory_purchase_inbound (scope_type, scope_id);
CREATE INDEX IF NOT EXISTS idx_inventory_purchase_inbound_inbound_date ON inventory_purchase_inbound (inbound_date DESC);

COMMENT ON TABLE inventory_purchase_inbound IS '采购入库单';
COMMENT ON COLUMN inventory_purchase_inbound.scope_type IS '数据范围：PLATFORM/GROUP/STORE';
COMMENT ON COLUMN inventory_purchase_inbound.scope_id IS '范围ID，平台固定0';
COMMENT ON COLUMN inventory_purchase_inbound.document_code IS '单据编号';
COMMENT ON COLUMN inventory_purchase_inbound.status IS '状态：草稿/已提交/已审核';

-- -----------------------------------------------------------
-- 2. 采购入库单行明细表
-- -----------------------------------------------------------
CREATE TABLE IF NOT EXISTS inventory_purchase_inbound_line
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    inbound_id  BIGINT         NOT NULL,
    item_code   VARCHAR(64)    NOT NULL,
    item_name   VARCHAR(128)   NOT NULL,
    quantity    NUMERIC(18,4)  NOT NULL,
    unit_price  NUMERIC(18,4)  NOT NULL DEFAULT 0,
    tax_rate    NUMERIC(10,4)  NOT NULL DEFAULT 0,
    created_at  TIMESTAMP      NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_inventory_purchase_inbound_line_inbound ON inventory_purchase_inbound_line (inbound_id);

COMMENT ON TABLE inventory_purchase_inbound_line IS '采购入库单行';

-- -----------------------------------------------------------
-- 3. 库存结存表
-- -----------------------------------------------------------
CREATE TABLE IF NOT EXISTS inventory_balance
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    scope_type     VARCHAR(16)   NOT NULL DEFAULT 'PLATFORM',
    scope_id       BIGINT        NOT NULL DEFAULT 0,
    warehouse_name VARCHAR(128)  NOT NULL,
    item_code      VARCHAR(64)   NOT NULL,
    item_name      VARCHAR(128)  NOT NULL,
    quantity       NUMERIC(18,4) NOT NULL DEFAULT 0,
    created_at     TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at     TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_inventory_balance_scope_wh_item UNIQUE (scope_type, scope_id, warehouse_name, item_code),
    CONSTRAINT ck_inventory_balance_scope_type CHECK (scope_type IN ('PLATFORM', 'GROUP', 'STORE'))
);

CREATE INDEX IF NOT EXISTS idx_inventory_balance_scope ON inventory_balance (scope_type, scope_id, warehouse_name);

COMMENT ON TABLE inventory_balance IS '库存结存';

-- -----------------------------------------------------------
-- 4. 库存流水表
-- -----------------------------------------------------------
CREATE TABLE IF NOT EXISTS inventory_transaction
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    scope_type     VARCHAR(16)   NOT NULL DEFAULT 'PLATFORM',
    scope_id       BIGINT        NOT NULL DEFAULT 0,
    biz_type       VARCHAR(64)   NOT NULL,
    biz_id         BIGINT        NOT NULL,
    biz_line_id    BIGINT,
    warehouse_name VARCHAR(128)  NOT NULL,
    item_code      VARCHAR(64)   NOT NULL,
    item_name      VARCHAR(128)  NOT NULL,
    quantity_delta NUMERIC(18,4) NOT NULL,
    before_qty     NUMERIC(18,4) NOT NULL,
    after_qty      NUMERIC(18,4) NOT NULL,
    operator_id    BIGINT,
    created_at     TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_inventory_transaction_scope_type CHECK (scope_type IN ('PLATFORM', 'GROUP', 'STORE'))
);

CREATE INDEX IF NOT EXISTS idx_inventory_transaction_scope ON inventory_transaction (scope_type, scope_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_inventory_transaction_biz ON inventory_transaction (biz_type, biz_id);

COMMENT ON TABLE inventory_transaction IS '库存流水';
